### ISSUE TITLE
Winds Barbs Cut Off When Wind From The East

### ISSUE THREAD

**Issue by buffaloseven** [sharppy/SHARPpy#100]
I've been having a problem in Ubuntu 12.04 of the wind barb tails being cut off on the skew-t plot if the wind is from the east. Played with it, and everything seems to work fine if `self.rpad` is adjusted.

From `/SHARPpy/sharppy/vis/skew.py`:

`Line 26:    self.lpad = 30; self.rpad = 50`

Change to:

`Line 26:    self.lpad = 30; self.rpad = 65`

I'd make an actual pull request, but don't have the ability to at the moment. If you'd rather this be submitted that way, I can do it early next week.

**Comment by wblumberg** [comment]
Hi @buffaloseven 

If you'd like to submit the pull request, we'd be happy to include it!  Thanks for noticing this bug and offering a change.  

Greg

**Comment by tsupinie** [comment]
I've committed this to the andover branch, so it will be fixed on the next release of SHARPpy.
