### ISSUE TITLE
Question:  Do the downloadable binaries get updated as changes are made to Master?

### ISSUE THREAD

**Issue by georgephillips1** [sharppy/SHARPpy#102]
It wasn't clear to me that when changes have been made to the Master branch, whether those get compiled into a new binary as well?  Or is it just the code that is updated and one needs to utilize that with Anaconda to get the fixes/enhancements? 

Thanks.

**Comment by tsupinie** [comment]
The binaries are updated whenever we release a new version. So bug fixes to Master in between releases won't necessarily show up in the binaries unless it's requested.
