### ISSUE TITLE
Publishing with the Journal of Open Research Software?

### ISSUE THREAD

**Issue by DamienIrving** [sharppy/SHARPpy#105]
I'm an Associate Editor with the [Journal of Open Research Software](http://openresearchsoftware.metajnl.com/) (JORS) and I'm also a climate science postdoc in Hobart, Australia. 

I was wondering if you'd considered publishing an article about SHARPpy with JORS? It's a fantastic way to get academic credit for the hard work involved in developing and maintaining scientific software.

**Comment by wblumberg** [comment]
@DamienIrving ...thank you so much for your recommendation!  We actually are in the process of finishing up our final revisions to a paper for the the Bulletin of the American Meteorological Society on this topic.  We'll have to talk about whether or not we want to try to submit something similar, but different to JORS!
