### ISSUE TITLE
PWV calculation

### ISSUE THREAD

**Issue by wblumberg** [sharppy/SHARPpy#108]
Something small that shouldn't affect too many users, but needs to be fixed...changing the parameter ptop in params.precip_water() to a pressure level above the minimum pressure in the sounding forces the program to extrapolate to ptop, effectively biasing the PW calculation.  Need to include some code to prevent this from happening in the future.

**Comment by tsupinie** [comment]
@wblumberg, have you fixed this or do you need me to? It looks like a 2-line fix.

**Comment by tsupinie** [comment]
I've pushed a small fix to both the master and andover branches for this.
