### ISSUE TITLE
Wheel Zoom Direction For Skew and Hodo Widgets

### ISSUE THREAD

**Issue by aarande** [sharppy/SHARPpy#110]
It would be good to make the wheel scroll direction for zooming on the skew and hodo widgets the same for both widgets. Right now you scroll up to zoom in the skew t and scroll down to zoom in on the hodo.

I would think scroll up for zooming in and scroll down for zooming out for both widgets.

**Comment by aarande** [comment]
Pull request has been done for fix to this issue

**Comment by tsupinie** [comment]
Yeah, that's probably a good change. Don't know why I coded it that way in the first place.
