### ISSUE TITLE
Phoenix, AZ point location may have incorrect lat/lon for forecast soundings

### ISSUE THREAD

**Issue by wxdevil** [sharppy/SHARPpy#113]
The point location for Phoenix, AZ (KPSR) generates incorrect forecast soundings. For example, the morning temperature in the NAM forecast sounding was in the 30s today. The site location is listed as KPSR. KPHX (Phoenix Sky Harbor) appears to be correct.

**Comment by tsupinie** [comment]
Ah, that would be because that site should be in central Wyoming. A few of the sites might be misplaced, issue #61 is dedicated to tracking those down. This one has been fixed in the latest version of the code.

Thanks!
