### ISSUE TITLE
STP, SCP, SARS, etc invalid for Southern Hemisphere

### ISSUE THREAD

**Issue by KenKato** [sharppy/SHARPpy#114]
Hi all,

My understanding is that all the parameters in Sharppy that use helicities based on cyclonic right-moving storms in the Northern Hemisphere are invalid for the Southern Hemisphere (SCP, STP, etc) as well as the SARS (it would presumably be trying to match mostly anticyclonic left-movers in the US), temperature advection and possibly the Potential Hazard Type as well (although I'm not sure on the latter).
Just wondering if there might be a fix somewhere on the horizon?

I did a search on here to see if anyone else had already raised this issue but couldn't find anything so I decided to post it on here.

P.S. keep up the brilliant work with Sharppy

**Comment by KenKato** [comment]
Just to clarify my previous post - it was based on the point and click web-based GFS soundings in the southern hemisphere from the world sector/domain at http://weather.cod.edu/forecast/

I also tried installing the 64-bit Windows 8.1 version in the Andover branch on Github but it (like the other pre-compiled binary executables of Sharppy) doesn't display any GFS soundings for any of the displayed locations in Australia after clicking the relevant model run, forecast time, location and the Generate Profiles button.

**Comment by swnesbitt** [comment]
This appears to be a common issue, here is an Argentinean implementation...

![img_1197](https://cloud.githubusercontent.com/assets/3288592/25431709/4dddab42-2a47-11e7-8eaf-ba903e16b799.JPG)

**Comment by wblumberg** [comment]
Hi guys...the Andover version will off the ability to switch out the storm motion vector used in all calculations to the left mover.  Andover will also address the backwards wind barbs issue.

As for the CoD implementation, we don't have any control over what versions they use of SHARPpy, and they've made some changes that depart from our original code base.  You may have to bug them to update their code.

I'm a little confused though about how you are able to run binaries of Andover.  We haven't made those yet.  Did you make those yourself?

I'm not able to reproduce the problem with loading in the Australia GFS soundings using the Xenia binary.  This may be an issue related to the data source.
