### ISSUE TITLE
Error while trying to open a user selected sounding

### ISSUE THREAD

**Issue by 1900hurricane** [sharppy/SHARPpy#115]
Hello,

While trying to open a .txt sounding I created using and reformatting source data from the University of Wyoming, I encountered the following error.

"zero-size array to reduction operation fmax which has no identity"

This perhaps reveals my status as a neophyte with regards to SHARPpy, but I am unsure of how to proceed. I am using v1.3.0 Xenia on MacOS 10.12.5. I'm grabbing data from [here](http://weather.uwyo.edu/cgi-bin/sounding?region=naconf&TYPE=TEXT%3ALIST&YEAR=1985&MONTH=06&FROM=0100&TO=0100&STNM=72520) and reformatting it like this.

[PIT 00Z 06:01:00.txt](https://github.com/sharppy/SHARPpy/files/969077/PIT.00Z.06.01.00.txt)

**Comment by wblumberg** [comment]
Hi @1900hurricane ...I've traced the problem to an issue with your data and the MCS Maintenance Probability function that runs in the program.  This function looks for data points between 6 and 10 km, and none exist in your data file.  This is where the program is choking.  I'll implement a fix into the master branch which hosts the Xenia version, but it will only appear in the source code and not the binary version of the program.

**Comment by 1900hurricane** [comment]
Awesome, thank you for your reply. I supplemented the sounding data with a 300 mb height from NARR (9430 m), and that allows it to run normally, fitting perfectly with the explanation you have given.

**Comment by tsupinie** [comment]
I just merged #116, so I'm going to go ahead and close this.
