### ISSUE TITLE
SHARPpy won't take 360 deg wind direction

### ISSUE THREAD

**Issue by georgephillips1** [sharppy/SHARPpy#118]
When converting an FSL archived raob to the format utilized for input by SHARPpy in the File -> Open method, the FSL output has 360 degrees for a due north wind.  Direct conversion to the file format needed to be opened by SHARPpy will result in an error opening the file because it doesn't like a wind direction >= 360 degrees.  Perhaps the positive values that are out of bounds can be restricted to >360 degrees?  

I realize I can substitute 0 degrees for 360 degrees in the conversion program, but if getting rid of the 360 degree restriction doesn't cause any other problems, it might be good to get rid of that.  Anybody in the future writing such converters wouldn't have to troubleshoot this issue.  

Attached are the file with the FSL output, the file that was converted for SHARPpy, and the error dialog box that details the reason for the error.  The 360 degree wind direction is at 775.5 mb.

[IAD.txt](https://github.com/sharppy/SHARPpy/files/1016308/IAD.txt)

[12103003.IAD.txt](https://github.com/sharppy/SHARPpy/files/1016309/12103003.IAD.txt)

![360degsharppyerror](https://cloud.githubusercontent.com/assets/12057398/26277505/ad0b091a-3d4e-11e7-875b-ab77036667db.jpg)

**Comment by wblumberg** [comment]
We agree.  This will be changed in the Andover branch and released in the next copy of SHARPpy.

**Comment by georgephillips1** [comment]
Thanks William.

**Comment by tsupinie** [comment]
I went ahead and pushed this to the master branch, so I'll go ahead and close the issue.
