### ISSUE TITLE
Custom Data Source from Launched Balloon

### ISSUE THREAD

**Issue by Curtis044** [sharppy/SHARPpy#121]
I downloaded the Windows Binary version of Sharppy. I created the new xml and csv file for my data. After I launch a balloon my data resides on the C drive. How do I get sharppy to recognize that my data is on the C drive so that when I open the sounding viewer it shows on the map so I can click it and view the data? Also, is there any command I need to type in after creating the xml and csv so it knows of my data? Thanks!

**Comment by wblumberg** [comment]
Hi @Curtis044 ...I think I understand what you're trying to do with this,  and theoretically it could be done, I'm not sure if it can be done with the binary version of the code right now.  You may be better off trying to set this up by downloading the source version of the code and trying to do this by installing and running the program via the command line.  The binary often assumes some things about the data source directory that we've found can make adding sources difficult.  I do not believe anything else needs to be done beyond setting up the .xml and .csv files and putting them in your .sharppy folder in your home directory.

**Comment by Curtis044** [comment]
@wblumberg Thanks for your reply, I appreciate it. I was trying to get the xml to read my C drive for the sounding, but it has never worked that way. I did find a way to display data from the C drive. Thank you again!

**Comment by Curtis044** [comment]
@wblumberg I still don't know what you put in the url of the xml file for data in the c drive to display, but if that's not possible, its ok.
