### ISSUE TITLE
Different Sounding import/export formats.

### ISSUE THREAD

**Issue by AlertIowa1234** [sharppy/SHARPpy#125]
Hello.
This is more of an enhancement idea that i was wondering if it would be possible to have multiple formats for sounding importing/exporting that can be read by SHARPpy, e.g CM1/WRF input_sounding, FSL, GSD, IGRA, etc. As i have spent way too many hours trying to convert and/or export these formats that can actually be viewed by SHARPpy. Just want to know if this is possible or not. Thanks.

**Comment by wblumberg** [comment]
This feature is possible, but someone would have to code it up by mimicking the various decoders that extend from the class specified in decoder.py.  Do you already have code to do this?

**Comment by mitchellkrogza** [comment]
Hi @AlertIowa1234 can you possibly show me an example of an FSL file and how it looks after you converted it. I am new to all of this but interested to be able to use FSL format from the NOAA database.

**Comment by wblumberg** [comment]
This thread has been dead for some time now.  Closing.
