### ISSUE TITLE
"Zero-size array to reduction operation minimum which has no identity"

### ISSUE THREAD

**Issue by hallettwx** [sharppy/SHARPpy#126]
Hello, 

Upon importing a custom sounding file (attached as [sounding.sharppy.txt](https://github.com/sharppy/SHARPpy/files/1428289/sounding.sharppy.txt)), I have received the error of: 

"zero-size array to reduction operation minimum which has no identity"

Looking back at a previous error (#115) this may be related to an internal algorithm within the program.

If it is not that, does SHARPpy need to read in files that have been converted to UNIX format within the Windows client? Or, am I missing something simple?

I am running the Windows 8.1/10 v 1.3 version of SHARPpy 

Thank you in advance.

**Comment by georgephillips1** [comment]
I'm seeing the same thing with the compiled version of sharppy on Win10.  However, I then downloaded the compiled Win7 64bit version, changed the compatibility mode for that executable in its properties to Win7, and it loaded your sounding just fine.  Weird.

**Comment by hallettwx** [comment]
I plotted the sounding in question without issue on the Windows 7 version running v1.3 as well. Perhaps a rare snag has been discovered.

**Comment by wblumberg** [comment]
That is strange that it'd be dependent upon that.  We'll look into that.  It could be that the binaries were just remade using different versions accidentally.

**Comment by wblumberg** [comment]
Closing because this thread has been inactive for over a year.
