### ISSUE TITLE
zero-size array to reduction operation fmax which has no identity

### ISSUE THREAD

**Issue by hallettwx** [sharppy/SHARPpy#130]
Upon attempting to load this custom sounding [test_sounding.txt](https://github.com/sharppy/SHARPpy/files/1462849/test_sounding.txt) I have recieved an error that states the following: "zero-size array to reduction operation fmax which has no identity."

This is especially strange as this is the same format as past soundings, and I believe all is formatted correctly.

I am running v1.3.0 on Windows 7 with 64bit architecture.

**Comment by Curtis044** [comment]
I believe the problem is that sharppy has to have data to at least 500mb in order to plot it.

**Comment by wblumberg** [comment]
Closing this because Andover fixes this issue.
