### ISSUE TITLE
No support for NAM 3km 

### ISSUE THREAD

**Issue by bfhouse** [sharppy/SHARPpy#131]
The High Resolution NAM has been transitioned from 4km to 3km and the current 4km NAM link is therefore broken. Would it be possible to add support for the new High Res NAM? If not at the very least could you remove the 4 km NAM option from the dropdown since it no longer works?

**Comment by tsupinie** [comment]
Hi, @bfhouse, the master branch should have the configuration for the 3km NAM added and the 4 km NAM removed. Download the latest version and let me know if that works for you.

**Comment by bfhouse** [comment]
So I looked through the source files and in those it is added. However, the
precompiled binaries are not up to date with the last modified date on the
.exe being 8/8/15. Being a bit more savvy myself I can install the source,
however, I know that many of my colleagues just install the binary so it
would be beneficial if those binaries could be recompiled and put on the
page.

**Comment by wblumberg** [comment]
We have some pre-release binaries of Andover that address this issue.  These new binaries have the 4-km NAM data source removed.
