### ISSUE TITLE
KRAP observed

### ISSUE THREAD

**Issue by smeagan** [sharppy/SHARPpy#133]
SPC recently changed, per NWS Rapid City's request, the identifier for Rapid City's observed sounding. Should be UNR instead of RAP. A simple change of that in the spc_ua.csv allows the Rapid City sounding to show up again.

I changed it on my version, and could submit the change but it may be quicker to just do it on your end.

Shane

**Comment by tsupinie** [comment]
I've updated spc_ua.csv to have the correct entry for Rapid City. Thanks for the heads up, @smeagan!
