### ISSUE TITLE
Error when using mlpcl

### ISSUE THREAD

**Issue by Silviameteoro** [sharppy/SHARPpy#138]
Hi All,

I am having an issue with the computation of parameters that use the mlpcl (please see below).

/usr/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/sharptab/interp.py:53: RuntimeWarning: divide by zero encountered in log10
return generic_interp_pres(np.log10(p), prof.logp[::-1], prof.hght[::-1])
/usr/lib64/python2.7/site-packages/numpy/lib/function_base.py:2059: UserWarning: Warning: converting a masked element to nan.
return interp_func([x], xp, fp, left, right).item()
/usr/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/sharptab/winds.py:45: UserWarning: Warning: converting a masked element to nan.
ps = np.arange(pbot, ptop+dp, dp)
Traceback (most recent call last):
File "sharppyreaderTESTE.py", line 86, in 
mlpcl = params.parcelx( prof, flag=4 ) # 100 mb Mean Layer Parcel
File "/usr/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/sharptab/params.py", line 1935, in parcelx
bulk_rich(prof, pcl)
File "/usr/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/sharptab/params.py", line 1994, in bulk_rich
mnlu, mnlv = winds.mean_wind(prof, pbot, p)
File "/usr/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/sharptab/winds.py", line 45, in mean_wind
ps = np.arange(pbot, ptop+dp, dp)
ValueError: arange: cannot compute length

I currently have numpy v. 1.14.2. 
I notice there is a “closed issue” about a similar problem when  it was suggested a downgrading to numpy v.1.12.1.

Is there any other potential available solutions? I am running on a server and downgrading the numpy version is not an option for me since there are other python applications running on this server.

I am working with python 2.7.5 on a Red Hat linux installation.

Thank you very much in advance!

Silvia

**Comment by wblumberg** [comment]
Hi Silvia.  I'm terribly sorry about getting to this now!  This was posted during my 'writing dissertation' phase.  I can't think of any other potential solutions.  Anaconda does offer the ability to build different environments, so perhaps you can make one with the needed Numpy installation.  Changes to numpy have made it extremely frustrating for us to keep SHARPpy working with several different numpy versions, and we keep running into new issues with each new numpy version.  We're trying to figure out a fix, but I'm not sure if that'll happen in the near future.

**Comment by wblumberg** [comment]
Our fix here will be to deploy SHARPpy on conda which will allow us to deploy the correct numpy version that works with this.
