### ISSUE TITLE
Average hail size not used in SARS

### ISSUE THREAD

**Issue by jscheel** [sharppy/SHARPpy#142]
https://github.com/sharppy/SHARPpy/blob/3b04a9dedaff51606af99393aeef1196b7b23189/sharppy/databases/sars.py#L319

It looks like the average size is calculated but not used anywhere. Should this data be provided somewhere?

**Comment by wblumberg** [comment]
My thought is no.   I believe that calculation code left over from when SARS was only run for hail and had its own individual inset, and the calibration for this feature isn't available to us (https://www.spc.noaa.gov/publications/jewell/sars.pdf).  SPC's forecast mission has often been to discriminate between SIG and NON-SIG hail (<2"), and SARS currently does this via a calibrated probabilistic output.  SPC has cautioned us about not deriving too much information from SARS given that there's a lot of overlap in the parameter space and the training dataset may be undersampling the true parameter space.

**Comment by jscheel** [comment]
Ah, that makes sense. If I understand you correctly, calculating a hail size here would be akin to re-assigning uniform weights to the outputs of weighted parameters and then averaging them. So, this is good to remove then?

**Comment by wblumberg** [comment]
Not quite.  The primary reason is that we're trying to follow what SPC has and they haven't used this feature in some time now - there are other outputs from SARS that meet their mission better.  I guess it could be removed, but doing so or considering it hasn't been a high priority given that this calculation isn't computationally expensive compared to other code and was in the original code they provided to us.
