### ISSUE TITLE
Segmentation Fault when Choosing Southern Hemisphere

### ISSUE THREAD

**Issue by mitchellkrogza** [sharppy/SHARPpy#143]
On Ubuntu 18.04 LTS when I select Southern Hemisphere there is an immediate segmentation fault and `full_gui.py` exits

![fault](https://user-images.githubusercontent.com/9961541/43458729-94aaddfc-94cb-11e8-8d46-b1c0aa00f5d0.PNG)

**Comment by mitchellkrogza** [comment]
I've now also tried on a fresh install of Debian using the Conda method and same problem with the Segmentation Fault. Has this repo been abandoned? I hope not.

**Comment by wblumberg** [comment]
Hi @mitchellkrogza ...the repo hasn't been abandoned.  A lot of our past developments have been experimental in that we need to transition this repo to include Python 3 and Pyside 2.  I'm in transition between jobs/moving right now and haven't been able to respond to anything posted.  It sounds like you're working with the Andover branch, which is our development branch.  I'm not sure how much support we can provide for this over the next few weeks, but if you post some detailed information about the individual steps you took to create this error (numpy, pyside, SHARPpy versions), I can probably take a swing at it once I get settled.

**Comment by wblumberg** [comment]
Hi @mitchellkrogza ...the repo hasn't been abandoned.  A lot of our past developments have been experimental in that we need to transition this repo to include Python 3 and Pyside 2.  I'm in transition between jobs/moving right now and haven't been able to respond to anything posted.  It sounds like you're working with the Andover branch, which is our development branch.  I'm not sure how much support we can provide for this over the next few weeks, but if you post some detailed information about the individual steps you took to create this error (numpy, pyside, SHARPpy versions), I can probably take a swing at it once I get settled.

**Comment by mitchellkrogza** [comment]
Hi @wblumberg great glad to hear this repo will still move ahead. Good luck with the new job and move. I'll post my installation methods tomorrow but believe I am pulling off master branch, didn't look to see if you had other branches.

**Comment by mitchellkrogza** [comment]
Should I try the HWT branch? Or stay away?

**Comment by tsupinie** [comment]
Hi, @mitchellkrogza. I don't have access to a Debian or Ubuntu box right now, and I'm unable to reproduce this on RHEL 6 (or Mac OS or Windows). Maybe I'll try spinning up a virtual machine later. My instinct is to say that the problem lies in the PySide binaries for those OSes, as Python errors will usually print a stack trace before crashing and/or burning.

**Comment by tsupinie** [comment]
Okay, I was able to reproduce this in a Debian VM. I'm not entirely sure what's going on, but it's something to do with the background threads. I've implemented what I think is a fix/workaround in the master-debian branch. Could you try that?

**Comment by mitchellkrogza** [comment]
Thanks @tsupinie I pulled from `master-debian` switched to that branch and ran `python ./setup.py install` again. It still segfaults if selecting Southern Hemisphere before I choose anything else. If I first choose GFS > and select a profile then I can switch to Southern Hemisphere and select a point on the map. But then it's still giving me this.

![sharppy](https://user-images.githubusercontent.com/9961541/43570645-2440edba-963b-11e8-9870-6e209e239f20.PNG)

I did download the Windows 7 64 Bit binary which works as suggested by @georgephillips1 but ultimately I would like this working in Linux. Let me know if there is anything else I can provide to help diagnose this.

**Comment by tsupinie** [comment]
Oh, yeah, you'll need to downgrade NumPy. NumPy v1.12 works for me. I need to get on and fix bugs in the latest versions because NumPy can't resist breaking SHARPpy whenever they do an update.

**Comment by mitchellkrogza** [comment]
Oh awesome I will try revert to Numpy 1.12 tomorrow and will revert back. Thanks so much @tsupinie

**Comment by mitchellkrogza** [comment]
Many thanks @tsupinie it works 100% with Numpy 1.12, now for me to start learning how to script with SharpPy 😂

**Comment by mitchellkrogza** [comment]
@tsupinie Is there any simple and quick way via the command line to create the basic graph layout already created within the SharpPy gui for a certain station name? I currently have no need to change what is produced simply to try and automate it daily.

![sharppy](https://user-images.githubusercontent.com/9961541/43643899-074a346c-972d-11e8-9b5c-9213466c5475.PNG)

**Comment by mitchellkrogza** [comment]
For others who may run into this issue, my steps are simply to
`conda uninstall numpy`
then
```
conda install numpy=1.12
cd SHARPpy/
python ./setup.py install
cd runsharp/
python ./full_gui.py
```

Tested on 
CentOS7 ✔️

**Comment by mitchellkrogza** [comment]
@tsupinie Happy to also report I have this working on Ubuntu 18.04 LTS
My install steps.

```
bash Miniconda2-latest-Linux-x86_64.sh
conda install -c conda-forge pyside=1.2.4
conda install numpy=1.12
git clone https://github.com/sharppy/SHARPpy.git
cd SHARPpy/
git pull origin master-debian
git checkout master-debian
python ./setup.py install
cd runsharp/
python ./full_gui.py
```

Initial 3-5 attempts to start `full_gui.py` might give you `NameError: global name 'socket' is not defined` keep trying to start it, it eventually fires up and generates the graphs needed.
