### ISSUE TITLE
Command Line Scripting to produce the Standard Graphing produced by full_gui.py

### ISSUE THREAD

**Issue by mitchellkrogza** [sharppy/SHARPpy#144]
Is there any guide to command line creation of the standard set of graphs already created within full_gui.py? 

I have two stations I need to create graphs for daily and the GFS Forecast Times needed (ie F000, F072) but want to try and achieve this without doing it through the gui which is a bit cumbersome.

Essentially I would like to be able to generate graphs something like this, excuse the crude syntax.

`GENERATE>STATION_NUMBER=FACT,FORECAST=F000 && SAVE PNG /wherever/file.png && SAVE TEXT /wherever/file.txt`

**Comment by wblumberg** [comment]
The updated version of SHARPpy will have something like this to plot soundings from the datasources listed in the program (See Commit fe47b8db55f11b6ed66351f3e0cc460f72a3e3c1).  It works well for observed soundings and data files, but right now it only plots the initial time step for forecast soundings.  If someone wants to extend what I already have there to include this, I'd say go ahead.  It will probably be something you put in full_gui.py.

**Comment by wblumberg** [comment]
For Andover; run $ sharppy -h  from the command line.
