### ISSUE TITLE
Question re: Microbust Composite Index formulation

### ISSUE THREAD

**Issue by tennessean** [sharppy/SHARPpy#146]
While looking at the [params.py](https://github.com/sharppy/SHARPpy/blob/master/sharppy/sharptab/params.py) page, I noticed a discrepancy regarding the Microburst Composite Index, specifically the currently programmed formulation vs. the described formulation.  I will try to explain the issue the best I can, in the hopes that someone will be able to help clear up my confusion.

The specific issue involves the use of the Total Totals parameter vs. the Vertical Totals parameter.

The description provided in the code (at lines 2737-2738) mentions the use of the Vertical Totals (note the emphasis):

>The Microburst Composite is a weighted sum of the following individual parameters: SBCAPE, SBLI, lapse rates, **vertical totals (850-500 mb temperature difference)**, DCAPE, and precipitable water.

However, the code contains the use of the Total Totals, which adds up the Vertical Totals and the Cross Totals parameters.

Line 2759:

```python
    tt = getattr(prof, 'totals_totals', t_totals( prof ))
```

Lines 2830-2841:

```python
    # Vertical Total Totals term
    if not utils.QC(tt):
        tt_term = np.nan
    else:
        if tt < 27:
            tt_term = 0
        elif tt >= 27 and tt < 28:
            tt_term = 1
        elif tt >= 28 and tt < 29:
            tt_term = 2
        else:
            tt_term = 3
```

Note on the latter that the comments section says "**Vertical Total** Totals term" (emphasis added).  In addition, the Total Totals value would usually be above 29 the majority of the time, which would make the "tt_term" equal to 3 quite often.

The question is this: Is this actually supposed to be the Vertical Totals, rather than the Total Totals?  Because if so, then it's possible that the original donated code is incorrect, which could potentially suggest that the SPC's implementation is in error (assuming that the code was correctly transposed from its original language into Python with**out** any errors).  Of course, there's also the possibility that there was an error in the code's translation and the Vertical Totals somehow became the Total Totals (or it was supposed to use the Total Totals, but with different limiting values).

If it was indeed supposed to use the Vertical Totals, then I offer some lines to correct this issue:

Line 2759 would become this:

```python
    vt = getattr(prof, 'vertical_totals', v_totals(prof)
```

Lines 2830-2841 would become this:

```python
    # Vertical Totals term
    if not utils.QC(vt):
        vt_term = np.nan
    else:
        if vt < 27:
            vt_term = 0
        elif vt >= 27 and vt < 28:
            vt_term = 1
        elif vt >= 28 and vt < 29:
            vt_term = 2
        else:
            vt_term = 3
```

Regardless, I would greatly appreciate it if someone could clear up any confusion that I have regarding this issue!

**Comment by wblumberg** [comment]
Good catch...hmmmmm.

**Comment by wblumberg** [comment]
I just checked the original code.  You're correct about these changes.  The vertical totals should be used, not the total totals.  I'll update the code.

**Comment by wblumberg** [comment]
Okay.  The master branch has been updated.  Thank you for catching this @tennessean !  We appreciate your careful eye here!
