### ISSUE TITLE
Update or re-label compiled SHARPpy files

### ISSUE THREAD

**Issue by georgephillips1** [sharppy/SHARPpy#148]
An issue over the past year with the Win10/8.1 compiled SHARPpy binary is that it has no sounding sites plotted to choose from for observed soundings.

Looking at the dates of the compiled versions, the Win10/8.1 binary is from Aug 8 2015 while the Win7 binary is from May 1 2016.  The Win7 binary **does** work okay for observed soundings.  Running the Win7 binary on Win10 appears to work just fine.  

My suggestion is to either update the Win10/8.1 binary to the latest code, or remove it and re-label The Win7 binary to Win10/8.1/7 to avoid confusing people who won't be able to get the Win10 version to work correctly.

**Comment by wblumberg** [comment]
I've made a change to the README to support this proposed change.
