### ISSUE TITLE
Problem with "tt_term not defined"

### ISSUE THREAD

**Issue by georgephillips1** [sharppy/SHARPpy#149]
I saw that SHARPpy had been updated for the microburst composite index to use VT instead of TT.  So from the sharppy directory I did a 

git pull origin master

and then 

python setup.py install

I didn't see any errors in this process, but now after choosing a sounding site and clicking on "Generate profiles", it doesn't plot the sounding and gives an error "global name 'tt_term' is not defined".  

![image](https://user-images.githubusercontent.com/12057398/45397760-1fd6d780-b607-11e8-852a-fe2d65dd080d.png)

**Comment by wblumberg** [comment]
Ah!  I didn't catch the final bug.  Try it now.

**Comment by georgephillips1** [comment]
That did it.  Thanks.

**Comment by wblumberg** [comment]
Woohoo!
