### ISSUE TITLE
Model Forecast Soundings have no PWV Climo coloring

### ISSUE THREAD

**Issue by wblumberg** [sharppy/SHARPpy#15]
Tim noticed this this week...the model forecast soundings on the HOOT site don't have the PWV climatology...even for locations that are very close to radiosonde sites.  He recommended we use the scipy.interpolate.griddata function to interpolate the PWV climatology mean and standard deviation values to other sites.  I'm unsure of how well interpolating STD values would go, but I think this should work.

The only other issue would be extrapolation of places beyond the PWV climatology.

**Comment by keltonhalbert** [comment]
I'm going to close this, as I don't see this being something addressed anytime soon, in addition to the fact that interpolating in between radiosonde sites for this data may not be very useful. If we decide to revisit this later, I will reopen it.
