### ISSUE TITLE
Error when using KTS2MS util

### ISSUE THREAD

**Issue by tennessean** [sharppy/SHARPpy#151]
I was testing the [Jupyter Notebook tutorial for SHARPpy](http://nbviewer.ipython.org/github/sharppy/SHARPpy/blob/master/tutorials/SHARPpy_basics.ipynb), specifically the code in the section labeled "Putting it all together into one plot" (namely the part of the code that allows the display for the various parameters), when I came across this issue while trying to test out the SHERB parameter's values:

```python
C:\Users\Public\Anaconda2\lib\site-packages\sharppy-1.3.0-py2.7.egg\sharppy\sharptab\params.pyc in sherb(prof, **kwargs)
   2306         p3km = interp.pres(prof, interp.to_msl(prof, 3000))
   2307         sfc_pres = prof.pres[prof.get_sfc()]
-> 2308         shear = utils.KTS2MS(winds.wind_shear(prof, pbot=sfc_pres, ptop=p3km))
   2309         sherb = ( shear / 26. ) * ( lr03 / 5.2 ) * ( lr75 / 5.6 )
   2310     else:

C:\Users\Public\Anaconda2\lib\site-packages\sharppy-1.3.0-py2.7.egg\sharppy\sharptab\utils.pyc in KTS2MS(val)
     84 
     85     '''
---> 86     return val * 0.514444
     87 
     88 

TypeError: can't multiply sequence by non-int of type 'float'
```

From what I understand (please correct me if I'm wrong), apparently the KTS2MS util isn't set as an integer, which is why it's spitting out this type of error.  Regardless of whether or not this is the case, I would recommend checking not only this but also *all* other utils just to be on the safe side.

Thank you.

**Comment by tennessean** [comment]
I decided to take a look at hot the KTS2MS util was being implemented on other parameters, and I found the source of the problem:

Line 2308, the problem line, is currently written as such:

```python
shear = utils.KTS2MS(winds.wind_shear(prof, pbot=sfc_pres, ptop=p3km))
```

When I changed it to this:

```python
shear = utils.KTS2MS(utils.mag(*winds.wind_shear(prof, pbot=sfc_pres, ptop=p3km)))
```

The error went away, and the SHERB parameter worked exactly as intended.

So the actual source of the problem was simply that a particular util was missing.

I just thought I'd help clear up the cause of that particular issue.

**Comment by wblumberg** [comment]
Ugh.  I could have sworn I fixed this issue back in Winter 2016 when it arose on a version of SHARPpy being used in Japan to identify high-shear low-CAPE tornadoes.  I've added your code @tennessean and will close this issue.  Thanks for submitting the correction!
