### ISSUE TITLE
Parameters below the skew t

### ISSUE THREAD

**Issue by Curtis044** [sharppy/SHARPpy#152]
How do we change these? I want to remove 1 or 2 of them and replace them with the freezing level and/or cap strength. Is there a straightforward way to do this, for someone who is not great at scripting? Thanks!

**Comment by wblumberg** [comment]
This is a function I think we've talked about adding at one time or another, but I don't think there's a clean way we've thought of to do this.  I'm not sure how much help I can provide to describe exactly what you want to do, but you'll want to look at sharppy/viz/thermo.py.  The drawIndices() function is what you'll want to look at as that draws all the index name and value in the table format.

**Comment by wblumberg** [comment]
Closing this unless someone makes a pull request (or makes an issue talking about their proposed changes to the code) with a clean way to do this.
