### ISSUE TITLE
Fixed Andover version for Windows

### ISSUE THREAD

**Issue by iaraUM** [sharppy/SHARPpy#159]
The fixed SHARPpy Andover version is not downloadable for windows.
I have tried to start a virtual machine for MAC OS, but my computer does not give me, please upload a version for Windows

**Comment by wblumberg** [comment]
Thanks for opening the issue.  We're aware of this issue and have been trying to fix it.  We had several things break in our release pipeline in the last month, and the Windows binary was one of the major parts that broke.  We haven't been able to get it fixed yet, but hopefully soon we'll figure out what's going wrong!

If you absolutely need Andover (which is still in the alpha stage), I recommend downloading the source code and installing from there.
