### ISSUE TITLE
ImportError: No module named sharppy.plot.skew

### ISSUE THREAD

**Issue by nuistly0451** [sharppy/SHARPpy#162]
Hello,all.
I download the example code(https://sharppy.github.io/SHARPpy/auto_examples/plot_sounding.html?highlight=plothodo),but  the program 'plot_sounding.py'  doesn't work.
It seems that there is no  'sharppy.plot' in  the SHARPpy lib.
Where can i get 'sharppy.plot' library?
Thank you!

**Comment by wblumberg** [comment]
That documentation is a part of the next release of our development branch of SHARPpy. That branch has the sharppy.plot library - the current release does not.  You can get it here: https://github.com/sharppy/SHARPpy/tree/andover/sharppy
