### ISSUE TITLE
pip3 install ?

### ISSUE THREAD

**Issue by captcha1** [sharppy/SHARPpy#167]
I'm running Fedora 30, and installed using pip3 (after install numpy, etc via "dnf") : 

 pip3 install --user sharppy

When I ran "sharppy", it complained with : 

 FileNotFoundError: [Errno 2] No such file or directory: '~/.sharppy/datasources/available.py'

So I copied a lot of the files from github.com/sharppy/SHARPpy/tree/master/datasources

... into ~/.sharppy/datasources

Now the GUI comes up, but I get errors like : 

 RuntimeError: Can't find converter for 'preferencesbox()' to call Python meta method.
 RuntimeError: Can't find converter for 'select_all()' to call Python meta method.

Can a pip3 install be made to work, or I should I install with "python setup.py install" ?

Thanks ...

**Comment by wblumberg** [comment]
Hi @captcha1 

Please use the python setup.py install.  I'm trying to release Andover in the next week or two, so it may be available via pip then.  The versions on pip and Conda right now aren't working.

Thanks,

Greg
