### ISSUE TITLE
use ma.log10 instead of np.log10 in interp.hght()

### ISSUE THREAD

**Issue by ahijevyc** [sharppy/SHARPpy#168]
Should ma.log10() be used at the end of the interp.hght() function instead of np.log10()?

    return generic_interp_pres(ma.log10(p), prof.logp[::-1], prof.hght[::-1])
 
I would like to avoid the log10 of zero warning, but don't want to break anything. I tried a pull request, but couldn't figure out how to isolate this change from the rest of my changes.

**Comment by wblumberg** [comment]
Hi @ahijevyc 

I went ahead and incorporated this change into Andover.  It passed all the tests, so it doesn't look like it's going to disrupt anything!  Thanks for the recommendation.

Greg
