### ISSUE TITLE
No Observed Soundings On OS X

### ISSUE THREAD

**Issue by cjn1979** [sharppy/SHARPpy#170]
When using SHARPpy for OS X the observed soundings map is blank, model soundings show fine. I am having the same issue as was reported here: https://github.com/sharppy/SHARPpy/issues/141

There was no solution posted on that thread. I am using the most recent pre-compiled binary for OS X, running OS X 10.12.6.

Any help is appreciated.

Thanks,
Chris

**Comment by wblumberg** [comment]
Hi Chris,

I'm working towards releasing the next version of Andover over the next two weeks, so please check back soon for a newer version.  I was able to generate a new binary last night, so there may be a new replacement then.  I had this same issue with that binary though.  

Greg

**Comment by cjn1979** [comment]
Thanks Greg, I'll check back.

Chris

**Comment by wblumberg** [comment]
Okay.  I found out what is causing this and fixed it.  Connections to the SPC site (where the observed soundings are hosted) now require a SSL certificate to connect via https.  Should work in the next version.

**Comment by cjn1979** [comment]
Thanks!
