### ISSUE TITLE
Can't install SHARPpy

### ISSUE THREAD

**Issue by Thermal21** [sharppy/SHARPpy#173]
I have tried to install SHARPpy a number different ways but it won't install.
Usually I get warnings about viruses and Trojans but this time I got the below message.
At this point I don't know what to do.  Any help would be greatly appreciated.
 
SHARPpy v0+unknown Andover-dev
Crash time: 2019-09-12 18:45:42.335298
Traceback (most recent call last):
  File "runsharp\full_gui.py", line 90, in doCrasher
  File "runsharp\full_gui.py", line 950, in createWindow
  File "runsharp\full_gui.py", line 761, in __init__
  File "runsharp\full_gui.py", line 767, in __initUI
  File "runsharp\full_gui.py", line 173, in __init__
KeyError: 'Observed'

**Comment by wblumberg** [comment]
Hi @Thermal21 ,

I'd encourage you to check back in about a week or two.  I'm not sure what steps you've taken so far, but I'm currently working on repairing the deployment pipeline so we can release Andover.  You should be able to install it through Conda once we're done.

Thanks,

Greg

**Comment by Thermal21** [comment]
Hi Greg,

Thanks for the quick reply.  I will be glad to wait until you have had a chance to fix things up.

All the best,

Bill Ross
907 441-5533
________________________________

**Comment by wblumberg** [comment]
Okay. Closing this since there's a new release on conda for the Andover beta.
