### ISSUE TITLE
Andover update issue

### ISSUE THREAD

**Issue by rpdale** [sharppy/SHARPpy#175]
Running Sharppy Andover just fine in WIn 10. This morning when I did a 'git pull origin master' in c:\Sharppy I got a fatal error because readme was unmerged and now I get:

error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

**Comment by wblumberg** [comment]
Hi Rob,

I'm not sure what the issue here is.  I would do a fresh download of the code.  Glad it works in your Windows 10 version (from what looks like Anaconda/git).  Our current issue is with the binaries, which are necessary for different federal entities.  

Thanks,

Greg

**Comment by rpdale** [comment]
Gotcha. Started with a fresh directory, and then noticed there's a new set of required files :) I could "conda install" all except PySide2 (which needed "pip install" - not sure I know the difference but anyways...)

Now I get:

No netCDF4 Python install detected. Will not be able to open netCDF files on the local disk. [That's always been there but never an issue]
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

This happens on my old 1.3 install too.

**Comment by wblumberg** [comment]
Yeah.  This is the issue (the qt.qpa.plugin) I'm currently dealing with in the binary - but it doesn't exist for me when I run the program from the command line.  Instead of installing PySide 2 from pip, use the Conda version.  Do a `conda install -c conda-forge pyside2`. You can also use the environment file included in the repository (environment.yml).  All dependencies should work using that file which can be installed by saying `conda env create -f environment.yml; conda activate devel'.

**Comment by rpdale** [comment]
I pip uninstalled pyside2 and used your command. That took a LONG time. Now I get:

Traceback (most recent call last):
  File "C:\Users\so_dale\miniconda3\Scripts\sharppy-script.py", line 11, in <module>
    load_entry_point('SHARPpy==1.4.0a4+98.g5bc9f224', 'console_scripts', 'sharppy')()
  File "C:\Users\so_dale\miniconda3\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\so_dale\miniconda3\lib\site-packages\pkg_resources\__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "C:\Users\so_dale\miniconda3\lib\site-packages\pkg_resources\__init__.py", line 2411, in load
    return self.resolve()
  File "C:\Users\so_dale\miniconda3\lib\site-packages\pkg_resources\__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\so_dale\miniconda3\lib\site-packages\sharppy-1.4.0a4+98.g5bc9f224-py3.6.egg\runsharp\full_gui.py", line 4, in <module>
    QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
AttributeError: type object 'PySide.QtCore.Qt' has no attribute 'AA_EnableHighDpiScaling'

**Comment by wblumberg** [comment]
Please remove that line from the code and let me know what happens!

**Comment by rpdale** [comment]
Had to remove line 4 and 5. Starts up and seems to work just fine now.

However executing your environment line conda activate devel (and I confirmed environment.yml is what's on the git) gives me:

Could not find conda environment: devel
You can list all discoverable environments with `conda info --envs`.

(base) C:\s2\SHARPpy>conda info --envs
# conda environments:
#
base                  *  C:\Users\so_dale\miniconda3
gallery                  C:\Users\so_dale\miniconda3\envs\gallery

This is the only error stream I'm seeing when running - seems to be more of an info than an error though:

c:\users\so_dale\miniconda3\lib\site-packages\numpy-1.15.4-py3.6-win-amd64.egg\numpy\lib\function_base.py:1308: UserWarning: Warning: converting a masked element to nan.
  return interp_func(x, xp, fp, left, right)
c:\users\so_dale\miniconda3\lib\site-packages\sharppy-1.4.0a4+98.g5bc9f224.dirty-py3.6.egg\sharppy\sharptab\thermo.py:107: RuntimeWarning: invalid value encountered in power
  return ((t + ZEROCNK) * np.power((p2 / p),ROCP)) - ZEROCNK

**Comment by wblumberg** [comment]
Looks good to me!  I don't know what's going on with your conda environments, but if it's running fine don't worry about it.  Thanks for the clear information!
