### ISSUE TITLE
SHARPpy Andover 1.4.0a5 Conda Package - Unable to start

### ISSUE THREAD

**Issue by Sandtato** [sharppy/SHARPpy#176]
**What kind of operating system are you using? What versions of the code, supporting packages, or Python are you using?**
Windows 10 1903 x64
Anaconda 2019.07 Python 3.7, with a separate Python 3.6.7 environment for SHARPpy
SHARPpy Andover 1.4.0a5 conda package

**Have you done any debugging of the problem(s)? If, so what steps did you take? Can you send screenshots showing your problem?**
When attempting to start SHARPpy from the directions on the github.io documentation for the conda package, I get the following error that is in the screenshot below:
![cmd_vToe2ZowfA](https://user-images.githubusercontent.com/23733013/65381468-078ca480-dcc0-11e9-8346-9192c4fcfdbf.png)
I have reinstalled Anaconda and the aforementioned separate environment with no success in resolving the issue.

**Have you checked to see if others have reported a similar problem?**
Yes, did not see any issues relating to this.

**Comment by wblumberg** [comment]
Hi @Sandtato. 

Thank you so much for the clear report on your issue!  I think I understand your problem.  I am not near my computer now, but I have an idea for a fix. Thank you again for letting me know - testing by others is helpful!

Greg

**Comment by Sandtato** [comment]
> Hi @Sandtato.
> 
> Thank you so much for the clear report on your issue! I think I see what’s causing your problem. The sharppy package is not installing into your home directory some of the necessary files because setup.py is not being run. I am not near my computer now, but I have an idea for a fix. Thank you again for letting me know - testing by others is helpful!
> 
> Greg

Thank you for your prompt response. I was able to get it working by downloading the 1.4.0a5 code manually from the GitHub and following that installation method. Just figured I'd pass this along in case anyone else encounters this issue. 😉

**Comment by wblumberg** [comment]
You’re very welcome. I also have an idea or two about the Windows 10 issue you mentioned. Looks like it’s a common problem with other packages. Would you be able to test a newer binary once I get it built again?

**Comment by Sandtato** [comment]
> You’re very welcome. I also have an idea or two about the Windows 10 issue you mentioned. Looks like it’s a common problem with other packages. Would you be able to test a newer binary once I get it built again?

I will be more than happy to test that for you.

**Comment by wblumberg** [comment]
CI generated binaries for Windows 10 and macOS are working now. Turns out the Windows 10 binary needed to have Python 3.6 instead of 3.7 - there was some issue with the SSL that this resolved.  The issue above has to do with the fact that the .sharppy directory is not installed when conda is used to install the program.  Not sure what to do about this yet, but running similar code in setup.py in full_guy.py might be a solution.

**Comment by wblumberg** [comment]
Closing this since @tsupinie and I figured out how to fix the conda installation and the Win 10 binary issues.  Should be doing a new release soon.
