### ISSUE TITLE
Win10 "tracing" issues v1.4.0b1

### ISSUE THREAD

**Issue by rpdale** [sharppy/SHARPpy#178]
Seems to be working fine. However with the Win10-64 binary I get message boxes popping up with "tracing..." about 50 times every time I run Sharppy, and every time I load a sounding, and every time I... :)

**Comment by wblumberg** [comment]
Ugh.  Was really hoping it would work this time, and we didn't see any of this behavior on the Win 10 machine I tested it on.  Can you get a screenshot for me, please?

**Comment by georgephillips1** [comment]
I'm seeing the same thing.

I ran this on two PCs and got the same popups.

**Comment by rpdale** [comment]
![Annotation 2019-11-09 125910](https://user-images.githubusercontent.com/11564694/68532913-1b807a00-02f1-11ea-87b5-fb498d75425b.gif)
![Annotation 2019-11-09 125911](https://user-images.githubusercontent.com/11564694/68532914-1c191080-02f1-11ea-838b-377980bdd08e.gif)

Looks like just some debug code left in there?

**Comment by wblumberg** [comment]
Yeah.  That looks like the debug code was left on.  I thought I had fixed that.  Let me rebuild the binaries and that should fix it.  Not sure if I'll get to that today though.

**Comment by wblumberg** [comment]
Also mentioned in Issue #182

**Comment by wblumberg** [comment]
Okay, I developed a new binary for Windows with the debugging turned off.  It can be found here:

https://github.com/sharppy/SHARPpy/releases/tag/v1.4.0b1

**Comment by wblumberg** [comment]
Looks like from Issue #182 this was fixed with this binary.  Could you confirm @georgephillips1 or @rpdale, please?

**Comment by rpdale** [comment]
All good - thanks!
