### ISSUE TITLE
v1.4.0b1 binary with no Python 3 installed

### ISSUE THREAD

**Issue by georgephillips1** [sharppy/SHARPpy#179]
On a PC with Anaconda python 3.7 installed, the SHARPpy v1.4.0b1 binary will run and work okay after closing all the tracing popup windows.  

On a PC with Anaconda python 2.7 installed, and on another with no version of python installed, the binary gives this error when clicking the Generate Profiles button.  This is the same type error for both observed and model soundings.

![sharppy_no_python3_err](https://user-images.githubusercontent.com/12057398/68532593-d5251e00-02e4-11ea-833b-7022d5c9c6fa.jpg)

**Comment by wblumberg** [comment]
Glad to hear Python 3.7 is working.  As 2.7 has become difficult and will reach end of life in a few months, we're not supporting it anymore, so I wouldn't worry about that.

**Comment by georgephillips1** [comment]
Greg,  I don't think you quite read my post right.  I'm saying that the binary doesn't work without Python 3 installed.  I thought it was just an executable, like the previous version from the Master branch, that would work whether any version of python was installed or not.

i.e. there is no guidance on the readme page  that we must have Ananconda python 3 installed in order to run the Windows 10 binary.  Was this intended?
