### ISSUE TITLE
Generate Profiles spawns a new process which doesn't quit when closing the sounding

### ISSUE THREAD

**Issue by dziban303** [sharppy/SHARPpy#182]
Win 10, Sharppy v1.4.0b1. 

After selecting a Sounding Source and a station, clicking Generate Profiles will bring up the sounding, but it will also spawn a new instance of Sharppy, which stays alive even after closing the sounding and returning to the Sounding Picker window. 

I might not have noticed this, except that when the new processes are spawned, along come the 50 debug tracing boxes. If you OK through all the tracing messages, the process quits. Ignoring the message boxes will leave the processes running even when closing Sharppy altogether, forcing you to manually end the processes in Task Manager (or clicking through all the OKs!)

Presumably this issue will be fixed when the tracing messages are fixed.

![image](https://user-images.githubusercontent.com/7931765/68552662-f0745400-03de-11ea-8f6c-5c053bbbf4b4.png)
![image](https://user-images.githubusercontent.com/7931765/68552671-0da92280-03df-11ea-8893-df1c69436f49.png)

![image](https://user-images.githubusercontent.com/7931765/68552593-3a106f00-03de-11ea-97cc-509a83afc3bd.png)

**Comment by wblumberg** [comment]
Okay, I developed a new binary for Windows with the debugging turned off.  It can be found here:

https://github.com/sharppy/SHARPpy/releases/tag/v1.4.0b1

**Comment by dziban303** [comment]
Thanks! Working normally; closing.
