### ISSUE TITLE
v1.4.1 crash on some models

### ISSUE THREAD

**Issue by rpdale** [sharppy/SHARPpy#183]
Both FV3s, the SSEF, and ULM GLM let me pick a location and time but then crash when I generate the profile.

![umglm](https://user-images.githubusercontent.com/11564694/68954792-b9ad8d80-0792-11ea-8f33-7d33e4b4d149.JPG)
![ssef](https://user-images.githubusercontent.com/11564694/68954795-badeba80-0792-11ea-9182-27f0535d38ac.JPG)
![fv3](https://user-images.githubusercontent.com/11564694/68954798-bc0fe780-0792-11ea-9e1c-f3ce28c8c9f5.JPG)

**Comment by wblumberg** [comment]
Hi @rpdale.  All three of those data sources are depreciated and are not available in the most recent version of Andover.  You should upgrade and delete your ~/.sharppy folder.

**Comment by rpdale** [comment]
Got bit by the old .sharppy issue finally :) I wondered why I didn't see them on my home machine.

**Comment by wblumberg** [comment]
For posterity's sake, this is for v1.4.0b.  v1.4.1 doesn't exist yet.
