### ISSUE TITLE
"screenshot"

### ISSUE THREAD

**Issue by rpdale** [sharppy/SHARPpy#184]
I think this has been going on a while but I never paid attention as it's not a big deal.

On Win10 system - when I start the binary, shortly after the program main screen pops up it creates a "screenshot" image in the working directory.

![screenshot](https://user-images.githubusercontent.com/11564694/68955278-aa7b0f80-0793-11ea-9f9c-e80e4f96d9af.png)

**Comment by wblumberg** [comment]
Ah.  That's code from debugging when the program gets run on continuous integration.  Not sure how to fix that right now as we need those screenshots.

**Comment by wblumberg** [comment]
Removed the code to do this in Commit ddea6f8 on the Andover branch.
