### ISSUE TITLE
Historical Sounding Availability

### ISSUE THREAD

**Issue by skewt33** [sharppy/SHARPpy#187]
I have tried v1.4.0 to v1.4.0b1 windows versions. I cannot access the historical soundings 
through the picker. For example, selecting an observed sounding source, the point and click
map is blank for any dates beyond what's available in the SPC soundings page. Is this a 
data source issue?

**Comment by tsupinie** [comment]
Sorry about the late response on this, but if you haven't figured out a way around this yet, could you delete your .sharppy directory and try again? It should be in your home directory (/Users/<username>/.sharppy on Windows).

**Comment by skewt33** [comment]
That worked...Thank you!
