### ISSUE TITLE
LFC?

### ISSUE THREAD

**Issue by cjn1979** [sharppy/SHARPpy#189]
I've seen two different ways of calculating the LFC. One method is to select the lowest level to the surface where the parcel becomes buoyant whereas SHARPpy selects the highest/last level where the parcel becomes buoyant. These methods can result in LFC values thousands of meters different. The issue occurs if there is more than one positive CAPE area in a sounding, where do you define the LFC is this case? Is one more correct than another?

Thanks,
Chris

**Comment by wblumberg** [comment]
SHARPpy defines it as the final location where the parcel becomes positively buoyant.  I don't have a great reason why other than this is how the codebase has always worked.  I don't remember but there's a Skew-T document that where the definition could be interpreted that way.  I don't have it readily available though.  SHARPpy's goal is more to provide consistency in the algorithms than to provide "correctness".  Correctness isn't something easily achievable in parcel theory, so I probably wouldn't put it that way.  There are a lot of arbitrary definitions.

**Comment by cjn1979** [comment]
Thanks for the reply. Soundings published by the NWS seem to agree with SHARPy but as you mentioned I've seen several definitions. I noticed one time that SHARPpy was different than the same sounding viewed with a different program for some parameters and I started digging into why. I guess as long as you understand how it's being defined then it might not be that important.

**Comment by wblumberg** [comment]
No problem!
