### ISSUE TITLE
Windows Binary. 

### ISSUE THREAD

**Issue by Ozzy405** [sharppy/SHARPpy#194]
Windows binary is still having the same errors. Also, is there a way to reduce how blurry the soundings are?

**Comment by wblumberg** [comment]
Hi there!  Thank you for your contribution.  Would you please submit the relevant information from this issue to Issue #193 please?  Also, I would appreciate it if you can open up a separate issue for the blurriness.

Please follow the contributing guidelines when opening up these issues!  It will help us keep track of everything much better.  I will close this issue until then.  Thanks!
