### ISSUE TITLE
SHARPpy v1.4.0b1 Bluriness

### ISSUE THREAD

**Issue by Ozzy405** [sharppy/SHARPpy#195]
My Sharppy is having issues as the soundings I am generating are quite blurry. I'm not sure if this is my issue, or if everyone else is having it.
![image](https://user-images.githubusercontent.com/62069964/76448731-0e9b9200-6388-11ea-91e5-57a39ddfbfc3.png)

**Comment by wblumberg** [comment]
Hi @Ozzy405 .  A picture does help me a bit more, but I do need more information from you.  Can you provide me more information about your system?

Please see the bug report section of this document for more ideas of what I'm looking for: https://github.com/sharppy/SHARPpy/blob/master/CONTRIBUTING.rst

**Comment by Ozzy405** [comment]
Whether or not it changed between versions is something I cannot answer. I have just recently began using sharppy.  I'm simply running the windows 10 binary version. If you are wanting more info about my system, i'm sure this picture should give you all you need. 
![image](https://user-images.githubusercontent.com/62069964/76451059-14937200-638c-11ea-9429-10867223ffcd.png)

**Comment by wblumberg** [comment]
Okay!  That's very helpful.  Can you tell me about your screen dimensions?

**Comment by Ozzy405** [comment]
I'm simply using 1080p 
![image](https://user-images.githubusercontent.com/62069964/76451494-bca93b00-638c-11ea-8aa5-66709958fd02.png)

**Comment by wblumberg** [comment]
Hmm.  That's a tough one.  I'd recommend changing those screen settings and maybe they'll help you out.  Otherwise I think we'd have to dig deep into the code.  I've never seen it show up that blurry unless the window size is super small.

**Comment by Ozzy405** [comment]
![image](https://user-images.githubusercontent.com/62069964/76453912-eebc9c00-6390-11ea-8516-da214544c61c.png)
This issue may be closed I suppose. I think it has something to do with the fact that i'm using a laptop instead of a desktop. I have to drop it to a very low % in order for it to not be blurred 
![image](https://user-images.githubusercontent.com/62069964/76453986-101d8800-6391-11ea-8ae7-972c1b4fb627.png)
This is how small we're talking.

**Comment by Ozzy405** [comment]
![image](https://user-images.githubusercontent.com/62069964/76454259-94700b00-6391-11ea-9053-754790405691.png)
Before you close I notice I cannot fit the entire sounding on my screen i'm not sure why

**Comment by wblumberg** [comment]
@Ozzy405 that would make sense.  I suspect (also from the picture you provided) that your laptop screen is rather small.  Glad you got it figured out!

Per the sounding - that's because the data for the sounding you loaded stopped at 300 mb.  If you look at the SPC site the same issue is on their website - https://www.spc.noaa.gov/exper/soundings/20031112_OBS/JAN.gif

**Comment by Ozzy405** [comment]
Yes i'm aware of that part. So i'm assuming the only way I can get a decent fit is if I mirror it to a monitor?

**Comment by Ozzy405** [comment]
I fixed the scaling completely and everything works perfectly. Thank you for the help.

**Comment by wblumberg** [comment]
You're welcome!  Glad we could figure out it.

**Comment by j-breeze** [comment]
Was having this same issue in Win10. It looks like SHARPpy adjusts the text/window size according to whatever "scale & layout" for text/ui the user has set in Display settings. I work on a 4K screen so my scale was set to 150%. This made everything blurry in the sounding and blew the boxes up so they went outside of the window (you could not see the Lapse Rates at the bottom left of the sounding, or Bunkers/Corfidi Shear for instance). Temporary work-around for me is to set to 100% scale, run SHARPpy, and then set back to 150%. Keeping it at 100% is a strain to see for the rest of the Windows GUI, and SHARPpy doesn't reset the scaling until the program is closed, so setting it back doesn't hurt.

Here's both the windows side-by-side at 100% and 150%.

<img width="1587" alt="sharppywindow" src="https://user-images.githubusercontent.com/86660909/123795912-fdcea280-d890-11eb-8c7f-bc80b7d669c7.png">
