### ISSUE TITLE
[BUG] Installing sharppy on a Mac using Anaconda cannot find Qt bindings in qtpy

### ISSUE THREAD

**Issue by sezick** [sharppy/SHARPpy#199]
<img width="1371" alt="Screen Shot 2020-04-22 at 9 54 14 AM" src="https://user-images.githubusercontent.com/31346680/79991898-c9877700-8480-11ea-8d26-6aa2f606aed6.png">
Hi, 

**Describe the bug**
I'm having an issue with running sharppy, after having installed it using anaconda package managers. I followed the [installation instructions in the documentation](https://sharppy.github.io/SHARPpy/install.html#installing-using-package-managers) by installing into its own Anaconda environment.

It seems as though there is an issue with the pyside version or installation, perhaps similar to the resolved issue #103, and perhaps the qtpy version as well.

**To Reproduce**
Here is the error I get when I attempt to run sharppy from the command line:

(sharppy-env) sezick@Stephanies-MacBook-Pro-3:~$ sharppy
Traceback (most recent call last):
  File "/opt/anaconda3/envs/sharppy-env/lib/python3.7/site-packages/qtpy/__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/sharppy-env/bin/sharppy", line 7, in <module>
    from runsharp.full_gui import main
  File "/opt/anaconda3/envs/sharppy-env/lib/python3.7/site-packages/runsharp/full_gui.py", line 1, in <module>
    from qtpy.QtGui import *
  File "/opt/anaconda3/envs/sharppy-env/lib/python3.7/site-packages/qtpy/__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')

**Versioning Information (please complete the following information):**
 - Device: MacBook Pro 2012
 - OS: El Capitan v10.11.6
 - SHARPpy Version: v1.4.0b1 (not sure why a beta version was installed?)
 - Dependency Versions: pyside v5.13.2) and qtpy v1.9.0 (see screenshot)
 - Screen dimensions [e.g. 4k, HD, 1920x800]: Intel Iris Pro 1536 MB 2880 x 1800
 - SHARPpy distribution type [e.g., git, conda, binary]: conda

Attached screen shot shows (part of) the Anaconda environment. 

Thanks,
Stephanie

**Comment by wblumberg** [comment]
Hi Stephanie, thanks for putting together a thorough bug report.  I'm going to modify the title to be a little more descriptive if that's okay.  This is quite an interesting bug.  SHARPpy should be defaulting to PySide2 and not PySide.  From the screenshot you have PySide2 installed.

I just looked at the documentation, and I think it needs to be updated.  There's a discrepancy between the documentation on the website and the latest version that I don't understand.  Try installing SHARPpy into a new environment just doing `conda install -c conda-forge sharppy`.  That should get v1.4.0 installed.  

From your environment, can you see if you can do a `import PySide2` from the Python prompt?

**Comment by sezick** [comment]
Yes, I can import PySide2, but I cannot import qtpy. I get the same error regarding PySide & qtpy bindings. See attached screenshot. 

<img width="650" alt="Screen Shot 2020-04-22 at 1 50 32 PM" src="https://user-images.githubusercontent.com/31346680/80015983-7e7d5c00-84a0-11ea-999f-598bb79d0a61.png">


> Hi Stephanie, thanks for putting together a thorough bug report. I'm going to modify the title to be a little more descriptive if that's okay. This is quite an interesting bug. SHARPpy should be defaulting to PySide2 and not PySide. From the screenshot you have PySide2 installed.
> 
> I just looked at the documentation, and I think it needs to be updated. It's very likely that's the source of our problem. There's a discrepancy between the documentation on the website and the latest version that I don't understand, and might be a symptom of something breaking in our deployment workflow. Try installing SHARPpy into a new environment just doing `conda install -c conda-forge sharppy`. That should get v1.4.0 installed.
> 
> From your environment, can you see if you can do a `import PySide2` from the Python prompt?

**Comment by wblumberg** [comment]
Hi Stephanie - What about installing sharppy from conda-forge into a brand new environment?  Did you try that yet?

**Comment by sezick** [comment]
HI Greg, Sorry I should have stated that I installed sharppy into a brand new environment, and now I have v1.4.0 installed. I am still encountering the same error with qtpy shown above.

**Comment by sezick** [comment]
I just upgraded my OS to macOS Catalina (10.15.4) and SharpPy is working just fine... thanks for your help!
