### ISSUE TITLE
SHARPpy looks funky on Windows

### ISSUE THREAD

**Issue by wblumberg** [sharppy/SHARPpy#21]
Here is the most recent Windows screenshot showing SHARPpy with Kelton's changes to the GUI uploaded on December 1st, 2014.  Looks like there are some positive changes with the thermo window, but more spacing is needed.

![testsharppy](https://cloud.githubusercontent.com/assets/7607087/5248768/c55d4b64-794b-11e4-83c7-ceaf704ad6fb.PNG)

**Comment by wblumberg** [comment]
@tsupinie has made some updates to the GUI in terms of making sure that the text within the insets isn't overlapping anymore.  Not sure when this part will be updated.

**Comment by keltonhalbert** [comment]
Closing this issue for the time being. Will upload an image of the fix implemented by @tsupinie in the AM.

**Comment by tsupinie** [comment]
How it looks as of my latest commits:
![20150416_00z_oun_snd1](https://cloud.githubusercontent.com/assets/885575/7173157/ac738c62-e3b8-11e4-9805-11141b0fc220.png)
![20150416_00z_oun_snd2](https://cloud.githubusercontent.com/assets/885575/7173158/aeae4ea4-e3b8-11e4-8682-cbeaab955573.png)

**Comment by tsupinie** [comment]
After some minor tweaks to the kinematics and storm slinky insets.
![20150416_00z_oun_snd1](https://cloud.githubusercontent.com/assets/885575/7173805/c46f92de-e3c2-11e4-9914-fcebd8e7ad88.png)
