### ISSUE TITLE
Convective Profile = NoneType

### ISSUE THREAD

**Issue by kylejgillett** [sharppy/SHARPpy#237]
Hello SHARPpy peeps, 

I am working on some custom scripting using SHARPpy and I am trying to create a convective profile, however, I am getting a strange error. First of all, the command to create the profile fails due to NoneType error when trying to execute `self.get_PWV_loc()`. As a test, when I run `print(Convect_prof)`, I get an output of 'None'. Any ideas as to what is causing this?

this is my code: `Convect_prof = profile.create_profile(profile='convective', pres=p.m, hght=z_clean.m, tmpc=T.m, \
                                    dwpc=Td.m, wspd=ws_clean, wdir=wd_clean, missing=-9999, strictQC=True)`

this is my error:
![Screenshot 2022-05-06 at 11-42-55 SkewTplotter - Jupyter Notebook](https://user-images.githubusercontent.com/100786530/167167602-12453374-ebbb-40a4-bf08-cf8a6205237f.png)

Thank you!

**Comment by kylejgillett** [comment]
I should add, this code is for an observed sounding from FWD yesterday.

**Comment by keltonhalbert** [comment]
The Convective Profile expects some specific keywords to be specified. In this case, it looks like the profile date isn't set. Add ```date=datetime(YYYY, MM, DD, HH)``` to your function call and it shouldn't complain anymore.

**Comment by kylejgillett** [comment]
> The Convective Profile expects some specific keywords to be specified. In this case, it looks like the profile date isn't set. Add `date=datetime(YYYY, MM, DD, HH)` to your function call and it shouldn't complain anymore.

Ah, I see! Thanks for the help, that fixed it!
