### ISSUE TITLE
STP Inset

### ISSUE THREAD

**Issue by keltonhalbert** [sharppy/SHARPpy#3]
The STP inset is having scaling issues, where the line through the distributions doesn't quite match up to the value in the left text inset. It has something to do with the top/bottom padding in the window. The issue is almost nonexistent on Mac, Linux tends to display the issue more.

**Comment by wblumberg** [comment]
We really should revisit this at some point.  This issue has been open for quite a while.

**Comment by kristinclemens** [comment]
Are this and other long-open bugs up for grabs by the OS community?

**Comment by wblumberg** [comment]
Hi @kristinclemens ...possibly.  I really forgot we had this bug open until I tried making some figures from the GUI the other day.  What did you have in mind?  There are different bugs and potential fixes that have different levels of changes needed to be made to the code.  This is probably a more minimal fix.  I know that in the past for ease-of-managment purposes we've been handling a lot of these bug fixes ourselves (some may require larger restructuring), so thanks for asking!

**Comment by wblumberg** [comment]
Fixed this in the Andover branch.  The y-axis labels no longer get displaced from the y-axis ticks, however during the resizing, I've noticed our redrawing speed has gone down.
