### ISSUE TITLE
Custom Data Sources

### ISSUE THREAD

**Issue by keltonhalbert** [sharppy/SHARPpy#40]
Something that has been suggested and needed is the ability to add custom data sources. With WFOs wanting to use it, in addition to PECAN, I think this is an excellent idea. I know @tsupinie has already been making progress in this direction. Opening issue for milestone tracking purposes.

**Comment by wblumberg** [comment]
I've been working with the modeling folks for PECAN on developing a text file format and URL path that we can link to, and I hope to have a good test file format soon.  This or alternative sources ought to be a good test of how best to instruct others on adding additional sources of data (i.e. WRF) to SHARPpy.  Perhaps there ought to be a request that those who develop their own SHARPpy sounding data sources online share those links with the community to maintain the spirit of the open data/source?  That's a data policy that is opening up a huge can of worms, so I would be in favor of at least making it be a request/suggestion (and not a requirement) made to users of the program.

**Comment by keltonhalbert** [comment]
As of right now, the XML structure for the custom data sources has been implemented. This will be released with the v1.2 El Reno '11 release. Given this, I am going to close the issue. 

Also, I like the data policy idea. Perhaps something to discuss further.
