### ISSUE TITLE
Skew-T Zooming

### ISSUE THREAD

**Issue by keltonhalbert** [sharppy/SHARPpy#42]
The current state of zooming in the Skew-T window is pretty pathetic, and could use a revisit.

**Comment by tsupinie** [comment]
I've got an idea for improving it and a branch in my own local copy dedicated to it.  It's essentially the same mechanics that are currently used in the updated picker for zooming/panning, just I hadn't worked out exactly how to get it to work when I was working on it in the Skew-T.

**Comment by keltonhalbert** [comment]
We have decided that this functionality will not be implemented in the v 1.2 release. Will remove it from the milestone.

**Comment by tsupinie** [comment]
I've been working on trying to get this nailed down.  Here is what I've come up with so far.  I'd say it's about 95% complete.

![20150514_22z_ksat_hrrr](https://cloud.githubusercontent.com/assets/885575/7632597/412c7410-fa14-11e4-8bb8-fc55c8da147b.png)

**Comment by keltonhalbert** [comment]
Going to close this issue since this will be addressed in the next release, and @tsupinie has already taken care of it.
