### ISSUE TITLE
Fix hodograph boundary motion vectors

### ISSUE THREAD

**Issue by wblumberg** [sharppy/SHARPpy#44]
After looking at Rich's workshop presentation, I need to fix the 9-11 SR Wind and 0-6 km shear vectors that are plotted on the hodograph when plotting the boundary motion vectors.  They are not plotted correctly.

**Comment by wblumberg** [comment]
I fixed this last night but I have not pushed the changes yet.  I've also fixed the Storm Mode calculations for the 0-6 km shear diagnosis, but I could not figure out the boundary-normal cloud layer speed difference bug yet.

**Comment by keltonhalbert** [comment]
Since Greg has just pushed his changes, will close this for the time being, since the other functionality has been temporarily removed.
