### ISSUE TITLE
Feature Request: Insert Sounding Text

### ISSUE THREAD

**Issue by thundersnow9** [sharppy/SHARPpy#45]
An awesome feature would be to be able to insert custom sounding text into the program via the GUI. If it could translate the Wyoming sounding format, it would be killer for nearly every archived sounding around the globe dating back into the 1970s. 

Like this one for example: http://weather.uwyo.edu/cgi-bin/sounding?region=naconf&TYPE=TEXT%3ALIST&YEAR=1999&MONTH=07&FROM=0300&TO=0300&STNM=72562

**Comment by keltonhalbert** [comment]
When you refer to custom sounding text, are you referring to custom data sources? i.e. the Wyoming files, SPC text files, etc?

**Comment by thundersnow9** [comment]
Yes

**Comment by keltonhalbert** [comment]
There is currently functionality to do this (albeit it doesn't work on linux for some reason), but not using the text format from Wyoming. I think adding a Wyoming decoder would be something very useful to have.
