### ISSUE TITLE
Color-blindness options

### ISSUE THREAD

**Issue by tsupinie** [sharppy/SHARPpy#50]
I was thinking that SHARPpy has a lot of color-contrast, which can be difficult for people who have color-blindness.  Especially the red/green variety, since it's the most common, and we have a lot of those colors.  So maybe it would be good to have an option for changing colors or something else for color-blindness.

**Comment by wblumberg** [comment]
@tsupinie could we address this in the changes you're making to the color scheme?

**Comment by tsupinie** [comment]
Yep, I plan to. :)

**Comment by wblumberg** [comment]
Added in Andover.
