### ISSUE TITLE
Add scipy and pillow to list of dependencies

### ISSUE THREAD

**Issue by aarande** [sharppy/SHARPpy#52]
Upon initial install of sharppy when I tried to run the full gui I got import errors regarding import of bytescale. It appears you need scipy and pillow for this to work and I was able to launch the gui after installing these using conda. These should be added to the docs along with PySide and numpy for dependencies.

**Comment by wblumberg** [comment]
Could you elaborate more on your distribution you are using for running it?  We have one record of this, but we may need more information on what's going on here.

**Comment by aarande** [comment]
Hi Greg, running Windows 7 and using the Anaconda Python distribution. I created a new python virtual environment using conda named sharppy and installed PySide and numpy and ran the setup.py install of SHARPpy. Once I tried to run the gui I got import errors for scipy.misc.bytescale and I believe the import was located in sharppy.viz.thetae line 4 from scipy.misc import bytescale. Once I did a conda install scipy and conda install pillow it worked and the gui came up.

**Comment by keltonhalbert** [comment]
I'm going to look into the extra dependencies, because I don't think those should be required. That being said, thank you for bringing this to our attention! I'll do some digging real quick and see if we can eliminate those imports.

**Comment by keltonhalbert** [comment]
@aarande, thank you for pointing this out. It appears that there were a number of unused scipy imports that got copied and pasted between sharppy.viz files. Could you see if this also removed the pillow dependency too?

**Comment by aarande** [comment]
Sorry for the delay...I just grabbed the newest release and went through the install and had no problems. Thanks guys and great work on this program! Great work on the selector map also...I had some ideas and code for this but looks like you have it.

**Comment by keltonhalbert** [comment]
Thanks for the feedback on the bug @aarande! And we're glad the new release is working well. Map selector credit definitely goes to @tsupinie - he was the workhorse behind that one.
