### ISSUE TITLE
0-3 km CAPE routine does not compute

### ISSUE THREAD

**Issue by wblumberg** [sharppy/SHARPpy#57]
The code to calculate the 0-3 km CAPE routine in parcelx() never gets run when running parcelx().

**Comment by tsupinie** [comment]
I messed with it this morning, and I was able to get it to compute *something.*  It's slightly off from what SPC has, though.
![image](https://cloud.githubusercontent.com/assets/885575/7183356/95fb4330-e41c-11e4-94aa-5e5c32c6cc42.png)

**Comment by keltonhalbert** [comment]
I'm going to close this since we seem to have it computing something. We can reopen it if we start to notice issues in the calculation.
