### ISSUE TITLE
Thermo Inset Missing Indices

### ISSUE THREAD

**Issue by keltonhalbert** [sharppy/SHARPpy#6]
The thermo inset is missing multiple indices.

**Comment by wblumberg** [comment]
Isaac Pato made a recommendation to make one of the indices the 0-3 MLCAPE.

**Comment by wblumberg** [comment]
I believe 0-3 km MLCAPE and VGP was also suggested by Kevin Polston.

**Comment by wblumberg** [comment]
Added the 0-3 MLCAPE to the thermo window.  Two spots remain.  Other options for indices include some of the ones I've just included:

- VGP
- EHI
- SHERB 
- Microburst Composite (MBURST)
- Derecho Composite Parameter (DCP)

**Comment by tsupinie** [comment]
Also, I'm not sure the 0-3 km CAPE routine is working properly. The sounding from the Washington, IL tornado should have some 0-3 km MLCAPE, but it's showing up as 0. BTW, it also seems to affect the ESP variable.

![image](https://cloud.githubusercontent.com/assets/885575/7174336/df94a7c6-e3cb-11e4-9b1e-a9cfba6ddaed.png)

**Comment by tsupinie** [comment]
(Sorry, let's continue this discussion here; didn't see you'd started commenting here)

Yeah, the SPC has 122 J/kg 0-3 km CAPE
![image](https://cloud.githubusercontent.com/assets/885575/7174372/5deccc2a-e3cc-11e4-9ecf-6e10a46d364b.png)

**Comment by wblumberg** [comment]
ESP also uses the 0-3 MLCAPE.  Makes me wonder if there's an issue with the routine that assigns the b3km attribute to the Parcel object.  It's worked in the past for me, but I don't remember if we've actually ever done some verification of that variable.

**Comment by tsupinie** [comment]
Might be best to keep those out until we can verify their correctness, then.

**Comment by wblumberg** [comment]
Have you found any instances where the 3CAPE is correct?  I find it hard to believe that it's always been wrong, because I believe in my checks ESP has been correct in the past.  Just trying to get an idea of whether or not the issue happens every time it runs.

**Comment by tsupinie** [comment]
No, I've checked against the Pilger, NE sounding (2014-06-16 19Z OAX) and the 2013-05-16 00Z FWD sounding.  Both of them should have non-zero 3CAPE.

**Comment by wblumberg** [comment]
Wow.  That's very surprising that a bug like this as gotten away from us this far into the development.  Hmmm.
