### ISSUE TITLE
el-reno reminder?

### ISSUE THREAD

**Issue by laufers** [sharppy/SHARPpy#60]
It took me several tries to run the current version of SHARPpy before I thought to re-run the setup.py install. You might want to reminder folks that have downloaded previous versions that they will need to do the same before starting the latest release.

**Comment by keltonhalbert** [comment]
Hi @laufers! 

We've definitely encountered a few instances where this is the case. I'll add a note the the top of the release and README.

**Comment by keltonhalbert** [comment]
I've added a reminder to the release page and README. We're hoping to alleviate this issue in the future with binary distributions.
