### ISSUE TITLE
Incorrect sounding placement for some sites

### ISSUE THREAD

**Issue by georgephillips1** [sharppy/SHARPpy#61]
Hi,

When downloading and viewing forecast soundings from KEMP, it is obvious it is for somewhere else.  All other nearby sounding sites appear to have soundings that correspond with what they look like in Bufkit.  KEMP is not even close.  

Looking in the databases folder at the model csv files, everything looks right for KEMP in terms of lat/lon, and the dot on the map is in the right location.  However, there are two entries each for the same site in the RAP, HRR, SREF and NAM files, i.e. two identical lines.  

In the GFS file, there is one line for KEMP, and another for 98009 with a slight difference in lat/lon.  The 98009 profile comes up correctly in sharppy and corresponds with what the Bufkit forecast soundings look like for Emporia.

This is with SHARPpy Beta v1.2.0 El Reno.

Thanks.

George Phillips

**Comment by tsupinie** [comment]
@georgephillips1, thanks for the heads up!  The points are associated with profiles based on the identifier, and the PSU bufkit server has some weird (absent?) naming conventions.  I'll have to dig through there and see where that sounding actually goes.

**Comment by tsupinie** [comment]
Okay, I've made some changes to the CSV files.  Turns out your "Emporia" sounding belongs in Emplande, Mexico, which PSU helpfully slapped an "emp" identifier on.  That and a few other out of place ones have been fixed.

I'm keeping this open for the possibility that other soundings will be out of place.

**Comment by dangoff** [comment]
This is a little more nitpicky, but the location name for WMO 72318 specified in spc_ua.csv file is incorrect - it's actually Blacksburg, VA (the UA facility is across the street from the NWS office).
