### ISSUE TITLE
Error on install and startup with 'nam4km'

### ISSUE THREAD

**Issue by georgephillips1** [sharppy/SHARPpy#62]
**I downloaded the latest build this morning and did the python install.  At the end of the install, the following error cropped up.  For both the initial install yesterday, and the update today, I downloaded the zip file and unzipped it into the C:\Anaconda directory, so the location of setup.py is C:\Anaconda\SHARPpy-master.  When updating, I made sure to choose to overwrite all**

=============================
Processing SHARPpy-1.2.0-py2.7.egg
removing 'c:\anaconda\lib\site-packages\SHARPpy-1.2.0-py2.7.egg' (and everything under it)
creating c:\anaconda\lib\site-packages\SHARPpy-1.2.0-py2.7.egg
Extracting SHARPpy-1.2.0-py2.7.egg to c:\anaconda\lib\site-packages
  File "c:\anaconda\lib\site-packages\SHARPpy-1.2.0-py2.7.egg\datasources\available.py", line 67
    'nam4km':lambda dt: _availableat_psu('nam4km', dt)
           ^
SyntaxError: invalid syntax

SHARPpy 1.2.0 is already the active version in easy-install.pth

Installed c:\anaconda\lib\site-packages\sharppy-1.2.0-py2.7.egg
Processing dependencies for SHARPpy==1.2.0
Finished processing dependencies for SHARPpy==1.2.0

===========================================

**When trying to run full_gui.py from the command line, it gives me the following error**

===========================================

C:\Anaconda\SHARPpy-master\runsharp>python full_gui.py
Traceback (most recent call last):
  File "full_gui.py", line 18, in <module>
    from datasources import data_source
  File "C:\Anaconda\lib\site-packages\sharppy-1.2.0-py2.7.egg\datasources\data_source.py", line 7, in <module>
    import available
  File "C:\Anaconda\lib\site-packages\sharppy-1.2.0-py2.7.egg\datasources\available.py", line 67
    'nam4km':lambda dt: _availableat_psu('nam4km', dt)
           ^
SyntaxError: invalid syntax

============================================

**Comment by Alingenomen** [comment]
Same problem here. Since updating the current installment of the Sharppy Package, I am also getting this error message.

**Comment by wblumberg** [comment]
Hi folks.  Thank you very much for reports and the descriptions of the bug.  From the output it looks like it's a syntax error, which should be pretty easy to fix.  Unfortunately we're at the end of our semester here at OU, and exams and projects are taking up most of our time, so our reliability on fixing bugs is a little sketchy.

**Comment by georgephillips1** [comment]
Is it possible the previous version could be reuploaded then, since this one can't even start?

There may be a way to download a previous version, but I am not sure how.

Thanks

George

**Comment by georgephillips1** [comment]
Sorry about the close and open events here.  I used the wrong button on the comment bar below.  :-)

**Comment by wblumberg** [comment]
That's alright.  Did you pull the recent version from the release page or did it come from the "master" branch?  If it's an issue with the release page version, then we'll look at it a bit closer.  Otherwise the most recent release should be able to run.

https://github.com/sharppy/SHARPpy/releases

**Comment by georgephillips1** [comment]
Thanks.  That link worked.  The pull was from the "master" and I was able to download the release page version.  It's working again.  I don't understand gethub very well.  :-)

**Comment by wblumberg** [comment]
Glad that's working!  Learning Github does take a little bit of time...

**Comment by tsupinie** [comment]
I'm sorry, I'm not sure how that slipped past.  Should be corrected now.  Both the syntax error and the bug I was trying to fix in the first place. >.<
