### ISSUE TITLE
Archive requested sounding files?

### ISSUE THREAD

**Issue by georgephillips1** [sharppy/SHARPpy#63]
This is a request for enhancement.  

Sometimes we download some pretty impressive/interesting sounding files.  If one doesn't make screen captures of the sounding display when viewing them, you can't really go back very far to regenerate them for image viewing/capturing purposes (a day for model soundings and a week for observed soundings).  It would be nice to be able to have the option to archive an interesting sounding file and load it again.  

Thanks.

George

**Comment by wblumberg** [comment]
@georgephillips1 , this is a rather good idea, and we talked a bit about your request yesterday.  I believe we have some code in place that can do this, and we'll be looking to add this function.  Thank you for the suggestion!

**Comment by keltonhalbert** [comment]
@georgephillips1 Thank you for the excellent suggestion! 

I have code that takes the sounding and prints it in the proper format to be read back in. It shouldn't be too hard to add this feature relatively soon. It might be a couple of weeks before it shows up, though - we're all students here, and finals week is upon us. That being said, we'll include this feature in the next patch!

**Comment by georgephillips1** [comment]
Excellent.  Thanks.  Of course since I put this request in, I've wondered if something else was possible in the archive arena.  

If this program is pulling the bufkit files from PSU as its data source, would it be possible to enable the program to read an archived bufkit sounding file?  We archive these regularly for certain sites and it would make looking back at cases with SHARPpy much easier.  

Thanks.

**Comment by wblumberg** [comment]
@georgephillips1, that certainly is possible, and we have the framework to read in files.  It's just a matter of when we get to this.  We'll add this to the list.

**Comment by keltonhalbert** [comment]
Since the original topic has been added to the latest release, will close issue.
