### ISSUE TITLE
Allow + and - keys to zoom in/out map

### ISSUE THREAD

**Issue by bctrainers** [sharppy/SHARPpy#64]
Greetings, right now I can zoom in and out on the Sounding Picker with my mouse wheel, then can click and drag as needed to the location to query for soundings. 

However, I had noticed that there isn't a zoom based keyboard key enabled, or coded in. Would it be possible to add in, or capture the + and - keys on the numpad/main-keyboard to zoom in and out? 

To demonstrate this a bit more visually on the idea... I set the mouse cursor to have focus in the map area. I would place the mouse cursor where I would like to zoom in at. I press the + or - keys to zoom in or out at that set point. The application will then zoom-to-point of where the mouse is at. 

I think Gibson Ridge software has a similar style when using the zoom with the mouse scroller to 'zoom-to-point'. Whereas here, it'd be keyboard and mouse pointer zoom-based, without the scroller.

edit; I appear to be unable to assign a label of 'enhancement'. :(

**Comment by wblumberg** [comment]
Hi @bctrainers .  Thank you for your suggestion!  This would be possible to do, and we'll make a note of this idea and see what we can do.

**Comment by keltonhalbert** [comment]
Hi @bctrainers - I've added this functionality to our experimental branch, and it will be included in the next version release of SHARPpy. Thanks for the suggestion!
