### ISSUE TITLE
Can't install on Windows 8.1

### ISSUE THREAD

**Issue by caleywoods** [sharppy/SHARPpy#68]
Running windows 8.1 with Anaconda 2.2 installed. Followed instructions and used ``conda install PySide`` to install PySide.

Error says:
![error](https://cloud.githubusercontent.com/assets/402957/7899892/caa48e18-06fc-11e5-9a89-ebabddd28d84.PNG)

**Comment by wblumberg** [comment]
Hi, it seems you forgot to include the "install" at the end of the "python setup.py install" string in the above command line input.  Without it, the script setup.py does not know you are installing the program.

**Comment by caleywoods** [comment]
Man.... Apparently it's been a long day. I'll give that a try.

**Comment by wblumberg** [comment]
Haha.  It happens!  Hope it works.

**Comment by tsupinie** [comment]
Given that @caleywoods hasn't responded, I'm going to assume that installation went well?

**Comment by caleywoods** [comment]
Worked great. Was an install for a friend. Thanks!
