### ISSUE TITLE
All Model Soundings Disappeared Suddenly

### ISSUE THREAD

**Issue by live4right** [sharppy/SHARPpy#70]
Hi,
My name is Carl, I have been a SkyWarn Spotter now for many years. I have really been enjoying the SHARPpy program for the past month or so since I installed it on my system. However today none of the model's will load only the observed sounding will. When I attempt to load a model sounding from the 4km NAM for example here is what I get in my command window:
Traceback (most recent call last):
  File "G:\Anaconda\SHARPpy\runsharp\full_gui.py", line 63, in finish
    callback(ret_val)
  File "G:\Anaconda\SHARPpy\runsharp\full_gui.py", line 441, in update
    self.run_dropdown.addItem(data_time.strftime(MainWindow.run_format))
AttributeError: 'str' object has no attribute 'strftime'

I hope it is nothing serious and it will be working again soon. Thanks for a great program and any help you provide

**Comment by wblumberg** [comment]
Hi @live4right ...we believe this is a server issue and is outside of our control for the time being.  The data can still be accessed every now and then, but it's slow.  It's possible they're doing work on it right now.

**Comment by live4right** [comment]
Hi,
Thanks for the quick reply, I really like that program so I'm glad it is just a server issue

**Comment by wblumberg** [comment]
You're welcome.  Glad you like the program!  :)
