### ISSUE TITLE
SPCWindow without GUI

### ISSUE THREAD

**Issue by krasting** [sharppy/SHARPpy#71]
Is it possible to generate the SPCWindow without the GUI?  I'd like to script the automatic generation the SPC-style plots of some real-time HRRR forecast soundings for a few locations.

**Comment by wblumberg** [comment]
Hi @krasting ...it is possible, but it would be difficult to implement as I believe our recent changes to the program have made this process more cumbersome earlier releases.  Doing this may require some serious surgery in the SHARPpy code.  We've been tossing around a way to do this without using the GUI through the matplotlib package, but we're not certain when we're going to be able to implement this function.

**Comment by wblumberg** [comment]
Hi @krasting ...wanted to let you know that there is a batch mode that does this.  It'll be going into the next version of SHARPpy that does this.  There's a copy of it on the andover branch (our development branch) if you want to investigate further.
