### ISSUE TITLE
Sharptab __init__.py has removed module sars in __all__ declaration

### ISSUE THREAD

**Issue by aarande** [sharppy/SHARPpy#73]
In sharppy.sharptab.__init__.py in the __all__ declaration the module 'sars' is included in the list but does not exist in sharptab. Causes problems when doing a from sharppy.sharptab import *

**Comment by tsupinie** [comment]
Sorry for the late response on this, but the sars module isn't in sharptab, it's in databases.  'sars' is in the `__all__` declaration in `sharppy/databases/__init__.py`.

**Comment by aarande** [comment]
Hi Tim...sorry for my late response also. I know it is in databases __all__ but the issue is it was left in the __all__ declaration in sharptab by mistake.

**Comment by keltonhalbert** [comment]
Hi @aarande - I've just corrected this in both the development and live branch. Thanks for the heads up and sorry it took so long to correct it.
