### ISSUE TITLE
full_gui.py not running [WIN7 x-64]

### ISSUE THREAD

**Issue by MJLMK** [sharppy/SHARPpy#74]
Installed Anaconda 2.3.0 on Win7 64 bit and then installed 1.3.0 Xenia and get error on running 

python full_gui.py

![error](https://cloud.githubusercontent.com/assets/13896654/9400126/a259ed34-478b-11e5-99eb-1deed16c439b.jpg)

any ideas here.

-Mark

**Comment by keltonhalbert** [comment]
Hi Mark,


We're still not entirely sure what causes this bug, but the bug can be fixed by doing one of two things:

1) delete the .sharppy folder in your home directory and rerun the setup script

If that doesn't work,

2) Delete your SHARPpy install in C:\Anaconda\lib\site-packages\ AND delete your .sharppy folder in your home directory and then rerun your setup script.

This has fixed the error for nearly everyone.

**Comment by MJLMK** [comment]
Thank you very much.  Simply deleting the .sharpy folder in my home directory solved the problem. 

-Mark

**Comment by live4right** [comment]
Hi, 
I know that this is an old thread, but I am having trouble with Windows7 32bit and the new SHARPpy 1.30 I don't know what could be different and I have done what you had mentioned in the previous posts. AS the error is exactly the same I followed the instructions, but the fixes did not work, I'm really sad that it stopped working as it was the best sounding software outside of AWIPS II. A possible additional feature the WBZ height and freezing level might be a nice addition to one of the insets. I understand how busy you guys are. Thank you for your hard work and a great program, 
![sharppy error](https://cloud.githubusercontent.com/assets/13044191/9938274/38a1928e-5d2a-11e5-916b-88c654a6ab7e.PNG)
I look forward to this bug getting resolved.

Sincerely,
Carl 
NWS Duluth Minnesota
Skywarn Spotter# AS 051

**Comment by MJLMK** [comment]
Carl,

Kelton's instructions above solved my problem.  I had to go to 
C:\users\<user name> and delete the .sharppy directory.  Once I did 
this, I re-installed the package and everything worked.

-Mark

**Comment by live4right** [comment]
Hi Mark,
Thanks for the help, thanks to you I discovered I missed a directory, now it works great again :D.
Thanks again 

--Carl

**Comment by keltonhalbert** [comment]
Glad that this worked!

I honestly don't know what broke in that directory between installs, but it seems like it's a relatively simple fix. 

I'm going to close the issue since it's resolved.
