### ISSUE TITLE
Error in Microburst Composite Index Code 

### ISSUE THREAD

**Issue by fairman** [sharppy/SHARPpy#82]
Hi guys-

There's an error in the microburst composite code (line 2768 in sharptab/params.py).  sbli_term is referenced in line 2768 whereas it most likely should be sbpcl.li5 as in earlier code.  Just wanted to let you know!

**Comment by wblumberg** [comment]
Hi @fairman ...

I'm having some trouble finding this error.  Line 2768 in the online code base doesn't have any reference to the "sbli_term".  Are you working off of the most recent version?

https://github.com/sharppy/SHARPpy/blob/master/sharppy/sharptab/params.py

Thanks,

Greg Blumberg

**Comment by fairman** [comment]
Argh, sorry, Greg.  It does look to be fixed in the latest commit. Thanks for the help!

**Comment by wblumberg** [comment]
Hey, no problem!  This is exactly the kind of participation from others we need to make this truly a quality community-based tool!
