### ISSUE TITLE
Previous Model Runs Not Displaying

### ISSUE THREAD

**Issue by live4right** [sharppy/SHARPpy#83]
Hi,
I noticed an issue for the past few days. With the upcoming severe weather event over the Tennessee Valley, I have wanted to compare various soundings for run to run consistency. However the dates and times show and I can select them. When I click generate profiles it says decoding then disappears and the sounding window never opens. I looked at the command prompts for errors yet found none. Its rather puzzling to me what might be wrong. I was curious as how I might be able to customize some of the colors on SHARPy, I will include a screen capture from the COD NEXLAB page demonstrating what I mean. I am not afraid of coding and scripting so you can be pretty thorough, I'd like to be able to match it as closely as possible as it really enhances the data in my opinion. I really love this program though, thanks for all your support.
--Carl Berghoff
NWS Duluth Minnesota
SkyWarn Spotter# AS051
![sharppy capture](https://cloud.githubusercontent.com/assets/13044191/11961224/da906b02-a89c-11e5-88e0-060cc39b8ef6.PNG)

**Comment by tsupinie** [comment]
As for your issues with the previous soundings, it's looking for the wrong file for some reason. I'm not sure if that's a bug someone introduced or if PSU changed the naming conventions for the files on us. Anyway, I'll see if I can have a patch up soon.

As for the customizability, Victor Gensini of COD did a lot of the modifications for the colors himself. I heard tell he was interested in checking the code in, but I haven't heard much beyond that.

**Comment by live4right** [comment]
Hi Tim,
Thanks for the quick reply, Merry Christmas and Happy New Year :D
​

**Comment by tsupinie** [comment]
Are you using one of the pre-compiled binaries or are you running the actual source code?

**Comment by live4right** [comment]
Hi,

I am running it from the source code. I downloaded the masterzip file and
installed it with Python.

**Comment by tsupinie** [comment]
Okay, I checked in a patch earlier. Could you download the code again and verify it works?

**Comment by live4right** [comment]
Good Morning,
Sorry it took so long to get back to you, I was having a good snooze, I
will check out the new code and let you know if it works.

--Carl

**Comment by live4right** [comment]
Hi,

I don't know what happened but now even the normal model soundings won't
load. I re-downloaded the source code and reinstalled the program 3 times
and I get the same result. The observed soundings load fine. There is
nothing in the error log though.

--Carl

**Comment by live4right** [comment]
Hi again,
 I realized I forgot to send you a capture from my install log where I
finally found the error, It seems it doesn't like something on line 5 of
the available.py. It claims there is an invalid syntax. Now the whole
program wont load. Did I reinstall something incorrectly or is there a
glitch in the new file? Thanks

--Carl

**Comment by live4right** [comment]
Cant believe I forgot the pic again; oops!
Here it is...

**Comment by live4right** [comment]
Found some more errors I will send yet another picture 
![error2](https://cloud.githubusercontent.com/assets/13044191/11977585/c1e02432-a949-11e5-8ea5-7f68d123474f.PNG)

**Comment by tsupinie** [comment]
Huh. I just download the zip file and everything ran fine for me. Try deleting your C:\Users\Richard\.sharppy\ directory and re-installing.

**Comment by live4right** [comment]
Hi Tim, 
The problem was on my part with the doc type html error (blushes) I selected save target as instead of copying the text data and pasting it in NotePad then naming it. Sorry for inconveniencing you, and thanks for the support :)
P.S I contacted Dr. Gensini about customizing the SHARPpy interface and he said that he would be happy to help me after the holidays )

--Carl

**Comment by tsupinie** [comment]
You're welcome! It happens. :)
