### ISSUE TITLE
full_gui.py won't launch, invalid syntax

### ISSUE THREAD

**Issue by MetNL** [sharppy/SHARPpy#91]
I just installed SHARPpy onto my D:\ drive in windows using conda.
When I try running full_gui.py from command I get an "invalid syntax" error:

> [sharppy2] D:\backup\files\SHARPpy-master\SHARPpy-master\runsharp> python full_gui.py
>    File "full_gui.py", line 73
>       print msg
>                    ^
>
>  SyntaxError: invalid syntax

**Comment by tsupinie** [comment]
Are you by chance using Python 3.x? Currently, SHARPpy only works with Python 2.7; this is a limitation of the libraries we use.

**Comment by MetNL** [comment]
Yes, I am on 3.5. I'll try a new environment with 2.7 and report back

2016-04-12 17:59 GMT+02:00 Tim Supinie <notifications@github.com>:

**Comment by MetNL** [comment]
Yes, everything is working now! Thanks for your support!

2016-04-13 11:28 GMT+02:00 Mathijs Strijards <towapr@gmail.com>:

**Comment by tsupinie** [comment]
You're welcome!
