### ISSUE TITLE
GFS out to 384hrs?

### ISSUE THREAD

**Issue by live4right** [sharppy/SHARPpy#92]
Hello,
This is more of an enhancement question, I noticed that the GFS on SHARPpy goes out to 180hrs when the College of Dupage Soundings on the GFS go the full 384hrs which is also powered by SHARPpy. I was wondering what do I have to do to configure my SHARPpy installation to go the full 384 hrs on the GFS. Thanks for your time.

Best Regards,
Carl

**Comment by tsupinie** [comment]
SHARPpy uses the Penn State Bufkit server for the GFS soundings, and the forecasts on that site only go out 180 hours. So that's why that limit exists, and it's probably not going away anytime soon, unfortunately. But we'll keep it in mind.
