### ISSUE TITLE
single file compile

### ISSUE THREAD

**Issue by jonrdouglas** [sharppy/SHARPpy#93]
This is more of a question than an issue. How are we compiling a single file binary for win64?

**Comment by tsupinie** [comment]
We used a separate program called [PyInstaller](http://www.pyinstaller.org/) to compile the binaries. It takes something called a "spec" file, of which we have one for each of several OSes in the runsharp/ directory.

You shouldn't need to do that, though. The binaries are linked from the documentation under the "[Installing SHARPpy](https://github.com/sharppy/SHARPpy#installing-sharppy)" section. Unless you really want to, then go ahead. :)

**Comment by jonrdouglas** [comment]
I do want to. I tried pyinstaller but got an error when running the exe. I made not changes to anything before running it so I was wondering how it was accomplished. G

**Comment by jonrdouglas** [comment]
it compiles but when i launch the exe, make my selctions, then try to generate a profile it opens the decoding dialog, closes the decoding dialog, and then nothing.  looking back at my pyinstaller debug i see:

12279 INFO: Processing hook   hook-PySide.QtGui.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Jonathan\Anaconda2\lib\site-packages\PySide\__init__.py", line 41, in <module>
    _setupQtDirectories()
  File "C:\Users\Jonathan\Anaconda2\lib\site-packages\PySide\__init__.py", line 37, in _setupQtDirectories
    QtNetwork.QSslSocket.supportsSsl()
AttributeError: 'module' object has no attribute 'QSslSocket'
12358 ERROR: Cannot find PySide plugin directories
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Jonathan\Anaconda2\lib\site-packages\PySide\__init__.py", line 41, in <module>
    _setupQtDirectories()
  File "C:\Users\Jonathan\Anaconda2\lib\site-packages\PySide\__init__.py", line 37, in _setupQtDirectories
    QtNetwork.QSslSocket.supportsSsl()
AttributeError: 'module' object has no attribute 'QSslSocket'
12430 ERROR: Cannot find PySide plugin directories
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Jonathan\Anaconda2\lib\site-packages\PySide\__init__.py", line 41, in <module>
    _setupQtDirectories()
  File "C:\Users\Jonathan\Anaconda2\lib\site-packages\PySide\__init__.py", line 37, in _setupQtDirectories
    QtNetwork.QSslSocket.supportsSsl()
AttributeError: 'module' object has no attribute 'QSslSocket'
12509 ERROR: Cannot find PySide plugin directories
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Jonathan\Anaconda2\lib\site-packages\PySide\__init__.py", line 41, in <module>
    _setupQtDirectories()
  File "C:\Users\Jonathan\Anaconda2\lib\site-packages\PySide\__init__.py", line 37, in _setupQtDirectories
    QtNetwork.QSslSocket.supportsSsl()
AttributeError: 'module' object has no attribute 'QSslSocket'
12583 ERROR: Cannot find PySide plugin directories
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Jonathan\Anaconda2\lib\site-packages\PySide\__init__.py", line 41, in <module>
    _setupQtDirectories()
  File "C:\Users\Jonathan\Anaconda2\lib\site-packages\PySide\__init__.py", line 37, in _setupQtDirectories
    QtNetwork.QSslSocket.supportsSsl()
AttributeError: 'module' object has no attribute 'QSslSocket'

what version of pysides, numpy, pyinstaller, anaconda, etc, did you use to build?

**Comment by jonrdouglas** [comment]
i did a full reinstall of anaconda pyinstaller and pyside. when i compile it i get, "pyi_rth_pkgres returned -1" after exe file is run. a quick google says to downgrade to setuptools to 19.2. after doing this it will run but not show profiles. looking at the debug i see

 "15960 INFO: Adding redirect Microsoft.VC90.MFC version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
16900 WARNING: Attempted to add Python module twice with different upper/lowercases: PyQt4.QtCore
16902 WARNING: Attempted to add Python module twice with different upper/lowercases: PySide.QtCore
16905 WARNING: Attempted to add Python module twice with different upper/lowercases: PySide.QtGui
16908 WARNING: Attempted to add Python module twice with different upper/lowercases: PySide.QtNetwork
16911 WARNING: Attempted to add Python module twice with different upper/lowercases: PySide.QtOpenGL
16913 INFO: Looking for eggs
16913 INFO: Using Python library c:\users\jonathan\anaconda2\python27.dll
16915 INFO: Found binding redirects:
[BindingRedirect(name=u'Microsoft.VC90.MFC', language=None, arch=u'amd64', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 6161), publicKeyToken=u'1fc8b3b9a1e18e3b'), BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch=u'amd64', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 9177), publicKeyToken=u'1fc8b3b9a1e18e3b')]
16953 INFO: Warnings written to C:\Users\Jonathan\iWedge\SHARPpy\runsharp\build\SHARPpy-win8-64\warnSHARPpy-win8-64.txt"

and around and round we go

**Comment by tsupinie** [comment]
On my OS X partition, I'm using PySide v1.2.2, Numpy v1.10.4, and PyInstaller v2.1. I'm not actually using Anaconda on my OS X partition (it's MacPorts for me), but I am using it on my Windows 7 partition. Unfortunately, I can't remember the version off the top of my head.

As for the errors, I'm really not sure. I had to fiddle around with the binary compilation for a while to get it to compile and work properly. Try doing print statements of a.scripts, a.binaries, etc. in the spec file to see what might be getting added or not added.
