### ISSUE TITLE
Low probability version issue

### ISSUE THREAD

**Issue by nguy** [sharppy/SHARPpy#97]
I was having trouble with installation, receiving the following error:
```
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    version.write_git_version()
AttributeError: 'module' object has no attribute 'write_git_version'
```

I discovered that I had an old package called ```version``` installed via pip. Since SHARPpy uses a less standard way to grab the version info (directly importing version through the setup.py at the beginning and therefore *not* in code directory) the "incorrect" system package version was being loaded instead of the SHARPpy package version script. Just to note many other packages use imports in the __init__.py file to avoid these conflicts and import the local version (of version in this case).

So I just wanted people to know the easy solution to this was to run ```pip uninstall version``` if you have the same situation.

**Comment by tsupinie** [comment]
I pushed a fix to the master branch that should eliminate name conflicts like that.

**Comment by nguy** [comment]
Thanks @tsupinie!
